/** Enkel land → flagg-emoji-koppling för spelarkortet. Fritextfält, så det här
 *  är en bästa-möjliga-matchning (case-insensitive), inte en strikt landkod. */
const COUNTRY_FLAGS: Record<string, string> = {
  sverige: "🇸🇪",
  sweden: "🇸🇪",
  norge: "🇳🇴",
  norway: "🇳🇴",
  danmark: "🇩🇰",
  denmark: "🇩🇰",
  finland: "🇫🇮",
  island: "🇮🇸",
  iceland: "🇮🇸",
  tyskland: "🇩🇪",
  germany: "🇩🇪",
  frankrike: "🇫🇷",
  france: "🇫🇷",
  spanien: "🇪🇸",
  spain: "🇪🇸",
  italien: "🇮🇹",
  italy: "🇮🇹",
  storbritannien: "🇬🇧",
  england: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
  skottland: "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
  scotland: "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
  uk: "🇬🇧",
  "united kingdom": "🇬🇧",
  irland: "🇮🇪",
  ireland: "🇮🇪",
  nederländerna: "🇳🇱",
  netherlands: "🇳🇱",
  belgien: "🇧🇪",
  belgium: "🇧🇪",
  portugal: "🇵🇹",
  polen: "🇵🇱",
  poland: "🇵🇱",
  österrike: "🇦🇹",
  austria: "🇦🇹",
  schweiz: "🇨🇭",
  switzerland: "🇨🇭",
  usa: "🇺🇸",
  "united states": "🇺🇸",
  "förenta staterna": "🇺🇸",
  kanada: "🇨🇦",
  canada: "🇨🇦",
  australien: "🇦🇺",
  australia: "🇦🇺",
  japan: "🇯🇵",
  sydkorea: "🇰🇷",
  "south korea": "🇰🇷",
  kina: "🇨🇳",
  china: "🇨🇳",
  sydafrika: "🇿🇦",
  "south africa": "🇿🇦",
};

export function flagForCountry(country?: string): string | undefined {
  if (!country) return undefined;
  return COUNTRY_FLAGS[country.trim().toLowerCase()];
}
