/** Speed Test – rå testnivå + stabiliserat Speed HCP för profil/spindel. */
export type MeasurementContext = "simulator" | "range";
export const SIMULATOR_DEVICES=["Trackman","Foresight (GC Quad/Hawk)","Garmin R10","Square Golf","SkyTrak","Annan simulator"] as const;
export const RANGE_DEVICES=["Toptracer Range","Trackman Range","Annan range"] as const;
export type Device=(typeof SIMULATOR_DEVICES)[number]|(typeof RANGE_DEVICES)[number];
export const SPEED_TOTAL_SHOTS=3;
export type SpeedShot={index:number;ballSpeed:number;clubSpeed?:number};
export function emptySpeedShots():SpeedShot[]{return Array.from({length:SPEED_TOTAL_SHOTS},(_,i)=>({index:i+1,ballSpeed:0}))}
export function mean(values:number[]):number{return values.length?values.reduce((a,b)=>a+b,0)/values.length:0}
type Anchor={hcp:number;value:number};
function interpolate(input:number,anchors:Anchor[]):number{const sorted=[...anchors].sort((a,b)=>a.hcp-b.hcp),first=sorted[0],last=sorted[sorted.length-1];if(input>=first.value)return first.hcp;if(input<=last.value)return last.hcp;for(let i=0;i<sorted.length-1;i++){const a=sorted[i],b=sorted[i+1];if(input<=a.value&&input>=b.value){const t=(a.value-input)/(a.value-b.value);return a.hcp+t*(b.hcp-a.hcp)}}return last.hcp}
const BALL_SPEED_ANCHORS:Anchor[]=[{hcp:-8,value:174},{hcp:-6,value:171},{hcp:0,value:161},{hcp:5,value:150},{hcp:10,value:140},{hcp:15,value:133},{hcp:20,value:126},{hcp:25,value:117},{hcp:36,value:97},{hcp:40,value:90}];
export function handicapFromBallSpeed(avgBallSpeed:number):number{return Math.max(-8,Math.min(40,interpolate(avgBallSpeed,BALL_SPEED_ANCHORS)))}
export const ALL_GOLFERS_BALL_SPEED={mean:126,sd:18};
const AGE_BALL_SPEED_BRACKETS=[{maxAge:25,mean:148,sd:12},{maxAge:35,mean:146,sd:12},{maxAge:45,mean:140,sd:12},{maxAge:55,mean:133,sd:11},{maxAge:65,mean:124,sd:10},{maxAge:200,mean:112,sd:10}];
export function ballSpeedDistributionForAge(age:number){return AGE_BALL_SPEED_BRACKETS.find(b=>age<=b.maxAge)??AGE_BALL_SPEED_BRACKETS[AGE_BALL_SPEED_BRACKETS.length-1]}
export function ballSpeedDensity(v:number,m:number,sd:number){const z=(v-m)/sd;return Math.exp(-.5*z*z)}
function erf(x:number){const sign=x<0?-1:1,ax=Math.abs(x),a1=.254829592,a2=-.284496736,a3=1.421413741,a4=-1.453152027,a5=1.061405429,p=.3275911,t=1/(1+p*ax);const y=1-((((a5*t+a4)*t+a3)*t+a2)*t+a1)*t*Math.exp(-ax*ax);return sign*y}
export function ballSpeedPercentile(v:number,m:number,sd:number){const cdf=.5*(1+erf((v-m)/(sd*Math.SQRT2)));return Math.max(1,Math.min(99,Math.round(cdf*100)))}
const SMASH_ANCHORS=[{hcp:-6,value:1.49},{hcp:0,value:1.47},{hcp:5,value:1.46},{hcp:10,value:1.44},{hcp:15,value:1.43},{hcp:20,value:1.41},{hcp:25,value:1.39}];
function expectedSmash(hcp:number){const s=[...SMASH_ANCHORS].sort((a,b)=>a.hcp-b.hcp);if(hcp<=s[0].hcp)return s[0].value;if(hcp>=s[s.length-1].hcp)return s[s.length-1].value;for(let i=0;i<s.length-1;i++){const a=s[i],b=s[i+1];if(hcp>=a.hcp&&hcp<=b.hcp){const t=(hcp-a.hcp)/(b.hcp-a.hcp);return a.value+t*(b.value-a.value)}}return s[s.length-1].value}
function scoreFromHandicap(hcp:number){return Math.round(Math.max(0,Math.min(100,100-(hcp+8)*(100/48))))}
export function handicapLabel(hcp:number){const v=Math.abs(hcp).toFixed(1).replace(".",",");return hcp<0?`+${v}`:v}
export function speedLevelLabel(score:number){if(score>=85)return"Elitnivå";if(score>=70)return"Stark nivå";if(score>=50)return"Bra nivå";if(score>=30)return"Grundnivå";return"Nybörjarnivå"}
export type SpeedResult={count:number;avgBallSpeed:number;topBallSpeed:number;avgClubSpeed?:number;topClubSpeed?:number;avgSmash?:number;handicap:number;score:number;analysis:string};
export function computeSpeedResult(shots:SpeedShot[]):SpeedResult{const played=shots.filter(s=>s.ballSpeed>0),balls=played.map(s=>s.ballSpeed),clubs=played.map(s=>s.clubSpeed).filter((v):v is number=>typeof v==="number"),avgBallSpeed=mean(balls),topBallSpeed=balls.length?Math.max(...balls):0,avgClubSpeed=clubs.length?mean(clubs):undefined,topClubSpeed=clubs.length?Math.max(...clubs):undefined,smashValues=played.filter(s=>s.clubSpeed).map(s=>s.ballSpeed/(s.clubSpeed as number)),avgSmash=smashValues.length?mean(smashValues):undefined,handicap=played.length?handicapFromBallSpeed(avgBallSpeed):0,score=played.length?scoreFromHandicap(handicap):0;return{count:played.length,avgBallSpeed,topBallSpeed,avgClubSpeed,topClubSpeed,avgSmash,handicap,score,analysis:buildAnalysis(avgBallSpeed,topBallSpeed,avgSmash,handicap)}}
function buildAnalysis(avg:number,top:number,smash:number|undefined,hcp:number){if(!avg)return"Genomför testet för att få din analys.";const parts:string[]=[],spread=top-avg;if(spread>=6)parts.push(`Din snabbaste putt (${top.toFixed(0)} mph) ligger ${spread.toFixed(0)} mph över snittet – stor variation mellan slagen tyder på inkonsekvent kontakt.`);else parts.push(`Jämn nivå mellan slagen, bara ${spread.toFixed(0)} mph mellan snitt och topp.`);if(smash!==undefined){const expected=expectedSmash(hcp);if(smash>=expected+.02)parts.push(`Smash factor ${smash.toFixed(2)} är bättre än snittet för din nivå (~${expected.toFixed(2)}).`);else if(smash<=expected-.02)parts.push(`Smash factor ${smash.toFixed(2)} ligger under snittet för din nivå (~${expected.toFixed(2)}).`);else parts.push(`Smash factor ${smash.toFixed(2)} matchar ungefär snittet för din nivå.`)}return parts.join(" ")}
export type SpeedSession={id:string;date:string;context:MeasurementContext;device:Device;shots:SpeedShot[];avgBallSpeed:number;topBallSpeed:number;avgClubSpeed?:number;/** stabiliserat Speed HCP när sessionen läses */handicap:number;/** rå HCP-nivå från just detta test */testHandicap?:number;score:number;notes?:string};
const KEY="golf-speed-sessions-v2",REAL_HCP_KEY="golf-real-handicap-v1";
function loadStored():SpeedSession[]{if(typeof window==="undefined")return[];try{const raw=window.localStorage.getItem(KEY),parsed=raw?(JSON.parse(raw) as SpeedSession[]):[];return Array.isArray(parsed)?[...parsed].sort((a,b)=>a.date.localeCompare(b.date)):[]}catch{return[]}}
function realHcp(){if(typeof window==="undefined")return null;const n=Number(window.localStorage.getItem(REAL_HCP_KEY));return Number.isFinite(n)?n:null}
/** WHS-inspirerat index: senaste 20 råa tester, bästa 8. Innan 8 tester finns
 * fylls indexet med spelarens riktiga HCP som startankare. Därefter får ett
 * enskilt test flytta indexet max 1,5 nedåt eller 0,8 uppåt. */
function indexedSeries(raw:number[],baseline:number|null){if(!raw.length)return[];const seed=baseline??raw[0];const out:number[]=[];for(let i=0;i<raw.length;i++){const recent=raw.slice(Math.max(0,i-19),i+1);const filler=Array(Math.max(0,8-recent.length)).fill(seed) as number[];const pool=[...recent,...filler].sort((a,b)=>a-b);const take=Math.min(8,pool.length);let target=pool.slice(0,take).reduce((a,b)=>a+b,0)/take;if(i===0){const delta=target-seed;target=seed+Math.max(-1.5,Math.min(.8,delta))}else{const prev=out[i-1],delta=target-prev;target=prev+Math.max(-1.5,Math.min(.8,delta))}out.push(Math.round(target*10)/10)}return out}
export function loadSpeedSessions():SpeedSession[]{const stored=loadStored();const raws=stored.map(s=>typeof s.testHandicap==="number"?s.testHandicap:s.handicap);const idx=indexedSeries(raws,realHcp());return stored.map((s,i)=>({...s,testHandicap:raws[i],handicap:idx[i]??raws[i]}))}
function persist(sessions:SpeedSession[]){const sorted=[...sessions].sort((a,b)=>a.date.localeCompare(b.date));window.localStorage.setItem(KEY,JSON.stringify(sorted));return sorted}
export function saveSpeedSession(shots:SpeedShot[],context:MeasurementContext,device:Device,notes?:string):SpeedSession{const r=computeSpeedResult(shots);const session:SpeedSession={id:crypto.randomUUID(),date:new Date().toISOString(),context,device,shots,avgBallSpeed:r.avgBallSpeed,topBallSpeed:r.topBallSpeed,avgClubSpeed:r.avgClubSpeed,handicap:r.handicap,testHandicap:r.handicap,score:r.score,notes:notes?.trim()||undefined};persist([...loadStored(),session]);return session}
export function deleteSpeedSession(id:string):SpeedSession[]{persist(loadStored().filter(s=>s.id!==id));return loadSpeedSessions()}
