import { createFileRoute, Link } from "@tanstack/react-router";
import { ChevronRight } from "lucide-react";
import { useEffect, useState } from "react";
import { computeEstimatedHandicap, loadRealHandicap, type CategoryHandicap } from "@/lib/sg-handicap";
import { computeStableCategoryHandicaps } from "@/lib/category-index";
import { LevelSummary } from "@/components/utveckling-overview";
import { RadarCard } from "@/components/progress-dashboard";

export const Route=createFileRoute("/utveckling/")({component:UtvecklingPage});
const DAY=86400000;
type Data={real:number|null;cats:CategoryHandicap[];pastCats:CategoryHandicap[];pastYearCats:CategoryHandicap[];totalHandicap:number|undefined;change90d:number|undefined};
function loadData():Data{const real=loadRealHandicap();const cats=computeStableCategoryHandicaps(undefined,real??undefined);const pastCats=computeStableCategoryHandicaps(new Date(Date.now()-90*DAY),real??undefined);const pastYearCats=computeStableCategoryHandicaps(new Date(Date.now()-365*DAY),real??undefined);const total=computeEstimatedHandicap(cats);const pastTotal=computeEstimatedHandicap(pastCats);return{real,cats,pastCats,pastYearCats,totalHandicap:total,change90d:total!==undefined&&pastTotal!==undefined?Math.round((total-pastTotal)*10)/10:undefined}}
function UtvecklingPage(){const[data,setData]=useState<Data|null>(null);useEffect(()=>setData(loadData()),[]);const hasData=(data?.cats.some(c=>c.count>0)??false);return <main className="mx-auto min-h-screen w-full max-w-md px-5 pb-28 pt-10"><p className="text-xs uppercase tracking-[0.3em] text-muted-foreground">SG4</p><h1 className="mt-2 font-display text-4xl leading-none">Analys</h1><p className="mt-3 text-sm leading-relaxed text-muted-foreground">Spindeln är din spelprofil. Se vilken kategori som sticker ut och öppna den för att förstå vad som ligger bakom nivån.</p>{!data?null:!hasData?<p className="mt-10 rounded-3xl border border-dashed border-border bg-card/50 p-6 text-center text-sm text-muted-foreground">Kör ditt första HCP-test för att börja bygga din SG4-profil.</p>:<div className="mt-6"><LevelSummary real={data.real} estimated={data.totalHandicap} change90d={data.change90d}/><RadarCard cats={data.cats} totalHandicap={data.totalHandicap} pastYearCats={data.pastYearCats}/><section className="mt-4"><p className="text-center text-[10px] font-semibold uppercase tracking-[0.18em] text-muted-foreground">Öppna kategori</p><div className="mt-2 grid grid-cols-2 gap-2">{data.cats.filter(c=>c.slug!=="speed").map(c=><Link key={c.slug} to="/utveckling/$slug" params={{slug:c.slug}} className="flex items-center justify-between rounded-2xl border border-border bg-card px-4 py-3 active:bg-tint"><span><span className="block text-xs text-muted-foreground">{c.title}</span><span className="mt-0.5 block font-display text-xl">HCP {c.handicap!==undefined?Math.abs(c.handicap).toFixed(1).replace(".",","):"–"}</span></span><ChevronRight className="h-4 w-4 text-primary"/></Link>)}</div>{data.cats.find(c=>c.slug==="speed")&&<Link to="/utveckling/$slug" params={{slug:"speed"}} className="mt-2 flex items-center justify-between rounded-2xl border border-border bg-card px-4 py-3"><span><span className="block text-xs text-muted-foreground">Speed</span><span className="block text-sm font-semibold">Fart & kraftöverföring</span></span><ChevronRight className="h-4 w-4 text-primary"/></Link>}</section></div>}</main>}
