import { useMemo, useState } from "react";
import { PolarAngleAxis, PolarGrid, PolarRadiusAxis, Radar, RadarChart, ResponsiveContainer, Tooltip } from "recharts";
import { ApproachRadarAnalysis } from "@/components/approach-radar-analysis";
import { AroundGreenRadarAnalysis } from "@/components/around-green-radar-analysis";
import { PuttingRadarAnalysis } from "@/components/putting-radar-analysis";
import { loadOffTeeSessions } from "@/lib/offtee-store";
import { distanceToHandicap, shotHandicap } from "@/lib/offtee";
import { BENCHMARK_LEVELS, hcpLabel, ratingFromHandicap, type CategoryHandicap } from "@/lib/sg-handicap";

type View="total"|"driving"|"approach"|"around"|"putting";
const TABS:[View,string][]=[["total","Total"],["driving","Off the Tee"],["approach","Approach"],["around","Around Green"],["putting","Putting"]];
const QUICK=BENCHMARK_LEVELS.filter(l=>["20","10","0","Tour"].includes(l.label));

function TotalRadar({cats,total}:{cats:CategoryHandicap[];total:number|undefined}){
 const[target,setTarget]=useState(QUICK.find(x=>x.label==="0")??QUICK[0]);
 const data=[...cats.filter(c=>c.slug!=="speed").map(c=>({subject:c.title,du:c.handicap!==undefined?ratingFromHandicap(c.handicap):0,target:ratingFromHandicap(target.categoryHcp?.[c.slug]??target.hcp),duHcp:c.handicap,targetHcp:target.categoryHcp?.[c.slug]??target.hcp})),{subject:"Totalt",du:total!==undefined?ratingFromHandicap(total):0,target:ratingFromHandicap(target.hcp),duHcp:total,targetHcp:target.hcp}];
 return <><div className="flex flex-wrap justify-center gap-2">{QUICK.map(l=><button key={l.label} type="button" onClick={()=>setTarget(l)} className={`rounded-full border px-3 py-1.5 text-xs font-semibold ${target.label===l.label?"border-chart-3 bg-chart-3/10 text-chart-3":"border-border text-muted-foreground"}`}>{l.label==="Tour"?"Tour":`HCP ${l.label}`}</button>)}</div><div className="mt-2 h-80 w-full"><ResponsiveContainer width="100%" height="100%"><RadarChart data={data} outerRadius="68%"><PolarGrid stroke="var(--border)"/><PolarAngleAxis dataKey="subject" tick={{fontSize:10,fill:"var(--muted-foreground)"}}/><PolarRadiusAxis domain={[0,110]} tick={false} axisLine={false}/><Radar dataKey="target" stroke="var(--chart-3)" fill="var(--chart-3)" fillOpacity={.12} strokeWidth={2}/><Radar dataKey="du" stroke="var(--chart-4)" fill="var(--chart-4)" fillOpacity={.28} strokeWidth={2.5} dot={{r:3,fill:"var(--chart-4)"}}/><Tooltip formatter={(v,n,p)=>[n==="du"?(p.payload.duHcp!==undefined?hcpLabel(p.payload.duHcp):"–"):hcpLabel(p.payload.targetHcp),n==="du"?"Du":target.label]}/></RadarChart></ResponsiveContainer></div><Legend compare={target.label==="Tour"?"Tour":`HCP ${target.label}`}/></>;
}
function DrivingRadar(){const[target,setTarget]=useState(QUICK.find(x=>x.label==="10")??QUICK[0]);const sessions=useMemo(()=>loadOffTeeSessions(),[]);const shots=sessions.flatMap(s=>s.shots.filter(x=>x.filled));if(!shots.length)return <Empty text="Registrera drives för att bygga analysen."/>;const avg=(a:number[])=>a.reduce((s,v)=>s+v,0)/a.length;const distHcp=distanceToHandicap(avg(shots.map(s=>s.total)));const overallHcp=avg(shots.map(s=>shotHandicap(s)));const fairway=shots.filter(s=>Math.abs(s.sidled)<=16).length/shots.length*100;const fairwayScore=Math.max(0,Math.min(100,fairway));const data=[{subject:"Längd",du:ratingFromHandicap(distHcp),target:ratingFromHandicap(target.hcp)},{subject:"Total driving",du:ratingFromHandicap(overallHcp),target:ratingFromHandicap(target.hcp)},{subject:"Fairway",du:fairwayScore,target:ratingFromHandicap(target.hcp)}];return <><div className="flex flex-wrap justify-center gap-2">{QUICK.map(l=><button key={l.label} type="button" onClick={()=>setTarget(l)} className={`rounded-full border px-3 py-1.5 text-xs font-semibold ${target.label===l.label?"border-chart-3 bg-chart-3/10 text-chart-3":"border-border text-muted-foreground"}`}>{l.label==="Tour"?"Tour":`HCP ${l.label}`}</button>)}</div><div className="mt-2 h-80 w-full"><ResponsiveContainer width="100%" height="100%"><RadarChart data={data} outerRadius="68%"><PolarGrid stroke="var(--border)"/><PolarAngleAxis dataKey="subject" tick={{fontSize:10,fill:"var(--muted-foreground)"}}/><PolarRadiusAxis domain={[0,110]} tick={false} axisLine={false}/><Radar dataKey="target" stroke="var(--chart-3)" fill="var(--chart-3)" fillOpacity={.12} strokeWidth={2}/><Radar dataKey="du" stroke="var(--chart-4)" fill="var(--chart-4)" fillOpacity={.28} strokeWidth={2.5} dot={{r:3,fill:"var(--chart-4)"}}/></RadarChart></ResponsiveContainer></div><Legend compare={target.label==="Tour"?"Tour":`HCP ${target.label}`}/></>}
function Legend({compare}:{compare:string}){return <div className="flex items-center justify-center gap-5 text-[11px] text-muted-foreground"><span className="inline-flex items-center gap-1.5"><span className="h-2.5 w-2.5 rounded-full bg-chart-4"/>Du</span><span className="inline-flex items-center gap-1.5"><span className="h-2.5 w-2.5 rounded-full bg-chart-3"/>{compare}</span></div>}
function Empty({text}:{text:string}){return <div className="flex h-80 items-center justify-center rounded-3xl border border-border bg-card text-sm text-muted-foreground">{text}</div>}

export function AnalysisRadarSwitcher({cats,totalHandicap}:{cats:CategoryHandicap[];totalHandicap:number|undefined}){
 const[view,setView]=useState<View>("total");
 return <section className="mt-6"><div className="rounded-3xl border border-border bg-card p-3">{view==="total"?<TotalRadar cats={cats} total={totalHandicap}/>:view==="driving"?<DrivingRadar/>:view==="approach"?<ApproachRadarAnalysis embedded/>:view==="around"?<AroundGreenRadarAnalysis embedded/>:<PuttingRadarAnalysis/>}</div><div className="-mx-1 mt-2 overflow-x-auto px-1 pb-1"><div className="flex w-max min-w-full justify-center gap-1.5">{TABS.map(([key,label])=><button key={key} type="button" onClick={()=>setView(key)} className={`shrink-0 rounded-full border px-3 py-1.5 text-[11px] font-semibold transition-colors ${view===key?"border-foreground bg-foreground text-background":"border-border bg-card text-muted-foreground"}`}>{label}</button>)}</div></div></section>;
}
