import { useMemo, useState } from "react";
import { PolarAngleAxis, PolarGrid, PolarRadiusAxis, Radar, RadarChart, ResponsiveContainer, Tooltip } from "recharts";
import { bunkerShots, collectAroundGreenShots, expectedScramblingPct, outside30Yards, type AroundGreenBenchmarkKey } from "@/lib/around-green-global";

const RADAR_BLUE="var(--chart-4)"; const RADAR_RED="var(--chart-3)";
type Metric={key:"scrambling"|"outside30"|"sandSave";subject:string;raw:number;benchmark:number;attempts:number};
const BENCHMARKS:Record<AroundGreenBenchmarkKey,{label:string}>={tour:{label:"PGA Tour"},hcp0:{label:"HCP 0"},hcp10:{label:"HCP 10"},hcp20:{label:"HCP 20"}};
const ORDER:AroundGreenBenchmarkKey[]=["tour","hcp0","hcp10","hcp20"];
function Tip({active,payload}:{active?:boolean;payload?:Array<{payload?:Metric&{benchmarkLabel?:string}}>}){if(!active||!payload?.length)return null;const r=payload[0]?.payload;if(!r)return null;return <div className="rounded-xl border border-border bg-card px-3 py-2 text-xs shadow-lg"><p className="font-semibold">{r.subject}</p><p className="mt-1 text-muted-foreground">Du: <span className="font-semibold text-foreground">{Math.round(r.raw)}%</span></p><p className="text-muted-foreground">{r.benchmarkLabel}: <span className="font-semibold text-foreground">{Math.round(r.benchmark)}%</span></p><p className="text-muted-foreground">{r.attempts} slag</p></div>}
export function AroundGreenRadarAnalysis({embedded=false}:{embedded?:boolean}){
 const[benchmark,setBenchmark]=useState<AroundGreenBenchmarkKey>("hcp10"); const shots=useMemo(()=>collectAroundGreenShots(),[]);
 const metrics=useMemo<Metric[]>(()=>{const outside=outside30Yards(shots),sand=bunkerShots(shots);return[
  {key:"scrambling",subject:"Scrambling",raw:expectedScramblingPct(shots),benchmark:expectedScramblingPct(shots,benchmark),attempts:shots.length},
  {key:"outside30",subject:"Utanför 30 yd",raw:expectedScramblingPct(outside),benchmark:expectedScramblingPct(outside,benchmark),attempts:outside.length},
  {key:"sandSave",subject:"Sand save",raw:expectedScramblingPct(sand),benchmark:expectedScramblingPct(sand,benchmark),attempts:sand.length},
 ]},[benchmark,shots]);
 if(!shots.length)return <div className="flex h-80 items-center justify-center rounded-3xl border border-border bg-card text-sm text-muted-foreground">Registrera närspelsslag för att bygga analysen.</div>;
 const data=metrics.map(m=>({...m,benchmarkLabel:BENCHMARKS[benchmark].label}));
 const body=<><div className="flex gap-2 overflow-x-auto pb-1">{ORDER.map(k=><button key={k} type="button" onClick={()=>setBenchmark(k)} className={`shrink-0 rounded-full border px-3 py-1.5 text-xs font-semibold ${benchmark===k?"border-chart-3 bg-chart-3/10 text-chart-3":"border-border text-muted-foreground"}`}>{BENCHMARKS[k].label}</button>)}</div><div className="mt-2 h-80 w-full"><ResponsiveContainer width="100%" height="100%"><RadarChart data={data} outerRadius="65%"><PolarGrid stroke="var(--border)"/><PolarAngleAxis dataKey="subject" tick={{fontSize:10,fill:"var(--muted-foreground)"}}/><PolarRadiusAxis angle={90} domain={[0,110]} tick={false} axisLine={false}/><Radar name={BENCHMARKS[benchmark].label} dataKey="benchmark" stroke={RADAR_RED} fill={RADAR_RED} fillOpacity={.12} strokeWidth={2}/><Radar name="Du" dataKey="raw" stroke={RADAR_BLUE} fill={RADAR_BLUE} fillOpacity={.28} strokeWidth={2.5} dot={{r:3,fill:RADAR_BLUE}}/><Tooltip content={<Tip/>}/></RadarChart></ResponsiveContainer></div><div className="flex items-center justify-center gap-5 text-[11px] text-muted-foreground"><span className="inline-flex items-center gap-1.5"><span className="h-2.5 w-2.5 rounded-full bg-chart-4"/>Du</span><span className="inline-flex items-center gap-1.5"><span className="h-2.5 w-2.5 rounded-full bg-chart-3"/>{BENCHMARKS[benchmark].label}</span></div></>;
 if(embedded)return <div>{body}</div>;
 return <section className="rounded-3xl border border-border bg-card p-4"><h2 className="font-display text-3xl">Analys around the green</h2><div className="mt-4">{body}</div><div className="mt-4 grid grid-cols-3 gap-2">{metrics.map(m=><div key={m.key} className="rounded-2xl border border-border p-3 text-center"><p className="text-[9px] uppercase tracking-[0.12em] text-muted-foreground">{m.subject}</p><p className="mt-1 font-display text-2xl">{m.attempts?`${Math.round(m.raw)}%`:"–"}</p><p className="text-[9px] text-muted-foreground">{m.attempts} slag</p></div>)}</div></section>;
}
