import { createPortal } from "react-dom";
import { useEffect,useMemo,useRef,useState } from "react";
import { ArrowLeft,Check,LoaderCircle,RotateCcw,Star,Undo2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Dialog,DialogContent,DialogDescription,DialogTitle } from "@/components/ui/dialog";
import { buildPuttingMatchReview } from "@/lib/putting-match-review";
import { handicapLabel } from "@/lib/shortgame";
import { useChipScreenColor } from "@/lib/use-chip-screen-color";\nimport { StandardHcpAnalysis,ShotAnalysisList } from "@/components/standard-hcp-analysis";
const DIST=[1.5,2.5,4,8,10,12,1.5,2.5,4],KEY="sg4-putting-nine-hole-v1",fmt=(n:number)=>n.toFixed(1).replace(".",",");
type Saved={id:string;at:number;putts:number[]};function load():Saved[]{try{const v=JSON.parse(localStorage.getItem(KEY)??"[]");return Array.isArray(v)?v:[]}catch{return[]}}function save(x:Saved){localStorage.setItem(KEY,JSON.stringify([...load(),x].slice(-30)))}
export function NineHolePuttingTest({onExit}:{onExit:()=>void}){
 const [view,setView]=useState<"intro"|"countdown"|"test"|"compiling"|"result">("intro"),[countdown,setCountdown]=useState(3),[putts,setPutts]=useState<number[]>([]),[compile,setCompile]=useState(0),[confirmExit,setConfirmExit]=useState(false),[analysis,setAnalysis]=useState(false),[hcpReady,setHcpReady]=useState(false);const timers=useRef<number[]>([]);
 useChipScreenColor(view==="countdown"||view==="compiling"||analysis);\n useEffect(()=>{const handler=()=>setConfirmExit(true);window.addEventListener("sg4-test-abort",handler);return()=>window.removeEventListener("sg4-test-abort",handler)},[]);const review=useMemo(()=>buildPuttingMatchReview(putts.map((p,i)=>({distance:DIST[i],yourValue:p,completed:true}))),[putts]);const best=typeof window==="undefined"?null:load().map(s=>s.putts.reduce((a,b)=>a+b,0)).reduce<number|null>((a,b)=>a===null?b:Math.min(a,b),null);
 const clear=()=>{timers.current.forEach(window.clearTimeout);timers.current=[]};useEffect(()=>clear,[]);useEffect(()=>{if(view!=="countdown")return;setCountdown(3);const start=performance.now(),duration=2400,id=window.setInterval(()=>{const left=Math.max(0,duration-(performance.now()-start));setCountdown(left/800);if(left<=0){window.clearInterval(id);setView("test")}},40);return()=>window.clearInterval(id)},[view]);useEffect(()=>{if(view!=="compiling")return;setCompile(0);clear();timers.current=[window.setTimeout(()=>setCompile(1),850),window.setTimeout(()=>setCompile(2),1750),window.setTimeout(()=>setCompile(3),2650),window.setTimeout(()=>setView("result"),3400)];return clear},[view]);useEffect(()=>{if(!analysis)return;setHcpReady(false);const r=window.matchMedia("(prefers-reduced-motion: reduce)").matches,id=window.setTimeout(()=>setHcpReady(true),r?0:1500);return()=>window.clearTimeout(id)},[analysis]);
 function start(){setPutts([]);setView("countdown")}function score(n:number){const next=[...putts,n];setPutts(next);if(next.length===9){save({id:crypto.randomUUID(),at:Date.now(),putts:next});setView("compiling")}}function abort(){clear();setConfirmExit(false);onExit()}const i=Math.min(8,putts.length),total=putts.reduce((a,b)=>a+b,0),maxStars=DIST[i]<=3?2:3;
 return <main className="mx-auto min-h-[calc(100dvh-58px)] max-w-md bg-slate-50 px-4 pb-[max(24px,env(safe-area-inset-bottom))] pt-4 text-slate-950"><Dialog open={confirmExit} onOpenChange={setConfirmExit}><DialogContent className="!z-[140] w-[calc(100%-32px)] max-w-sm rounded-3xl bg-white p-6"><DialogTitle className="text-2xl font-black">Avbryta testet?</DialogTitle><DialogDescription>Dina registrerade hål i det här testet sparas inte.</DialogDescription><Button onClick={abort} className="min-h-12 bg-slate-950 text-white">Avbryt test</Button><Button variant="outline" onClick={()=>setConfirmExit(false)}>Fortsätt testet</Button></DialogContent></Dialog>
 {view==="intro"?<div className="space-y-4"><section className="text-center"><p className="text-xs font-black uppercase text-blue-600">Putting Challenge</p><h1 className="mt-1 text-4xl font-black">Hur bra puttar du?</h1><p className="mt-2 text-sm text-slate-600">9 hål från korta, medellånga och långa avstånd. Ett Putting-HCP.</p></section><section className="rounded-3xl border border-blue-100 bg-white p-4 shadow-sm"><img src="/Putting_1.png" alt="" className="mb-4 h-52 w-full rounded-2xl object-cover"/><div className="grid grid-cols-3 divide-x rounded-2xl bg-slate-50 py-3 text-center">{[["9 hål","Standardtest"],["HCP","Analys"],["1,5–12 m","Alla längder"]].map(([a,b])=><div key={a}><Check className="mx-auto mb-1 h-4 w-4 text-blue-600"/><p className="text-xs font-black">{a}</p><p className="text-[10px] text-slate-500">{b}</p></div>)}</div><Button onClick={start} className="mt-4 min-h-14 w-full rounded-2xl bg-blue-600 text-base font-black text-white">Starta Putting-Test</Button></section>{best!==null&&<p className="px-2 text-sm font-semibold">Personbästa · {best} puttar</p>}</div>
 :view==="countdown"?<div className="fixed inset-0 z-[90] flex flex-col items-center justify-center bg-blue-600 text-center text-white"><p className="text-xs font-black uppercase tracking-[.18em] text-blue-100">Putting Challenge · 9 hål</p><h1 className="mt-3 text-3xl font-black">Gör dig redo</h1><p className="mt-2 text-blue-100">Startar om {Math.max(1,Math.ceil(countdown))}</p><div className="relative mt-8 h-40 w-40"><svg className="-rotate-90 h-full w-full" viewBox="0 0 100 100"><circle cx="50" cy="50" r="40" fill="none" stroke="currentColor" strokeWidth="5" className="text-white/20"/><circle cx="50" cy="50" r="40" fill="none" stroke="currentColor" strokeWidth="5" strokeLinecap="round" strokeDasharray="251.2" strokeDashoffset={251.2*(1-Math.max(0,countdown)/3)} className="text-white"/></svg><span className="absolute inset-0 flex items-center justify-center text-6xl font-black">{Math.max(1,Math.ceil(countdown))}</span></div></div>
 :view==="test"?<div className="space-y-4"><section className="text-center"><p className="text-xs font-semibold text-slate-500">Putting Challenge · 9 hål</p><h1 className="mt-2 text-4xl font-black">Hål {i+1}</h1><p className="mt-2 text-5xl font-black text-blue-700">{fmt(DIST[i])} m</p><div className="mt-3 flex justify-center gap-1">{Array.from({length:maxStars},(_,x)=><Star key={x} className="h-7 w-7 text-slate-200"/>)}</div></section>{i===8&&<p className="rounded-2xl border border-violet-200 bg-violet-50 px-4 py-3 text-center font-bold text-violet-900">Sista putten – en chans till att slå ditt rekord!</p>}<section className="rounded-3xl border border-blue-100 bg-white p-4"><p className="mb-3 text-center text-sm font-semibold text-slate-500">Hur många puttar?</p><div className="grid gap-2">{[[1,"1-putt"],[2,"2-putt"],[3,"3+ puttar"]].map(([n,l])=><Button key={n} variant="outline" onClick={()=>score(Number(n))} className="min-h-16 rounded-2xl text-lg font-black">{l}</Button>)}</div>{putts.length>0&&<Button variant="ghost" onClick={()=>setPutts(a=>a.slice(0,-1))} className="mt-2 w-full text-slate-500"><Undo2/>Ändra förra hålet</Button>}</section></div>
 :view==="compiling"?createPortal(<div className="fixed inset-0 z-[100] flex flex-col items-center justify-center bg-blue-600 p-6 text-center text-white"><span className="mb-7 flex h-16 w-16 items-center justify-center rounded-full bg-white text-blue-600">{compile>=3?<Check className="h-9 w-9"/>:<LoaderCircle className="h-9 w-9 motion-safe:animate-spin"/>}</span><h1 className="text-3xl font-black">{compile>=3?"Resultatet klart":"Sammanställer testet…"}</h1><div className="mt-6 space-y-4 text-left text-blue-100">{["Sammanställer dina nio hål","Beräknar puttingresultat","Förbereder din HCP-analys"].map((x,j)=><p key={x} className={`flex gap-3 ${j<=compile?"opacity-100":"opacity-0"}`}>{j<compile||compile>=3?<Check/>:<LoaderCircle className="motion-safe:animate-spin"/>}{x}</p>)}</div></div>,document.body)
 :view==="result"?<div className="space-y-4"><section className="rounded-3xl border border-blue-100 bg-white p-5 text-center"><p className="text-xs font-black uppercase text-blue-600">Ditt resultat</p><h1 className="mt-1 text-2xl font-black">Putting-Test klart</h1><p className="mt-4 text-5xl font-black text-blue-700">{total}</p><p className="text-sm text-slate-500">puttar totalt</p><div className="mt-5 grid grid-cols-3 gap-2 rounded-2xl bg-slate-50 p-4"><div><strong>{review.onePutts}</strong><p className="text-xs text-slate-500">1-puttar</p></div><div><strong>{review.threePutts}</strong><p className="text-xs text-slate-500">3+</p></div><div><strong>{fmt(review.average)}</strong><p className="text-xs text-slate-500">snitt</p></div></div></section><Button onClick={()=>setAnalysis(true)} className="min-h-14 w-full rounded-2xl bg-blue-600 font-black text-white">Visa min HCP-analys</Button><Button onClick={start} className="min-h-14 w-full rounded-2xl bg-slate-950 text-white"><RotateCcw/>Testa igen · 9 hål</Button></div>:null}
 <Dialog open={analysis} onOpenChange={setAnalysis}><DialogContent className="!fixed !inset-0 !h-[100dvh] !max-h-none !w-full !max-w-none !translate-x-0 !translate-y-0 !rounded-none !border-0 !bg-blue-600 !p-0 text-white [&>button]:text-white"><DialogTitle className="sr-only">Putting HCP-analys</DialogTitle><DialogDescription className="sr-only">Ditt estimerade Putting-HCP.</DialogDescription><StandardHcpAnalysis title="Putting HCP-analys" hcp={hcp??0} onClose={()=>setAnalysis(false)} slides={[{key:"shots",content:<ShotAnalysisList title="Dina nio hål" rows={putts.map((p,i)=>({label:`Hål ${i+1} · ${fmt(DIST[i])} m`,value:`${p===3?"3+":p} putt${p===1?"":"ar"}`,grade:p===1?"exceptionell":p===2?"bra":"svag"}))}/>},{key:"profile",content:<section><p className="text-sm font-bold uppercase tracking-widest text-blue-100">Din profil idag</p><h2 className="mt-3 text-3xl font-black">Putting per längd</h2><div className="mt-5 space-y-3">{[["Kort · 1,5–2,5 m",putts.filter((_,i)=>DIST[i]<=2.5)],["Medel · 4 m",putts.filter((_,i)=>DIST[i]===4)],["Lång · 8–12 m",putts.filter((_,i)=>DIST[i]>=8)]].map(([label,vals])=>{const v=vals as number[],a=v.length?v.reduce((x,y)=>x+y,0)/v.length:0;return <div key={label as string} className="flex justify-between rounded-2xl bg-white/10 p-4"><strong>{label as string}</strong><span>{fmt(a)} puttar</span></div>})}</div></section>},{key:"potential",content:<section className="text-center"><p className="text-sm font-bold uppercase tracking-widest text-blue-100">Din potential</p><h2 className="mt-4 text-3xl font-black">Din putting idag</h2><div className="mt-6 rounded-3xl bg-white/10 p-5 text-left"><p className="flex justify-between"><span>1-puttar</span><strong>{review.onePutts}</strong></p><p className="mt-3 flex justify-between"><span>2-puttar eller bättre</span><strong>{putts.filter(p=>p<=2).length} / 9</strong></p></div><p className="mt-5 text-blue-100">Bygg vidare på de hål där du redan presterar på Bra nivå eller bättre.</p></section>}]} /></DialogContent></Dialog>
 </main>
}