import { createPortal } from "react-dom";
import { useEffect, useMemo, useRef, useState } from "react";
import { ArrowLeft, Check, LoaderCircle, RotateCcw, Trophy, Undo2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogTitle } from "@/components/ui/dialog";
import { EXTENDED_PRECISION_TARGETS, emptyPrecisionShots, precisionResult, proximity, summarize, type PrecisionShot } from "@/lib/precision";
import { loadPrecisionSessions, savePrecisionSession } from "@/lib/precision-store";
import { handicapLabel } from "@/lib/shortgame";
import { useChipScreenColor } from "@/lib/use-chip-screen-color";
const TARGETS=[...EXTENDED_PRECISION_TARGETS] as number[],fmt=(n:number)=>n.toFixed(1).replace(".",",");
export function NineShotApproachTest({onExit}:{onExit:()=>void}){
 const [view,setView]=useState<"intro"|"countdown"|"test"|"compiling"|"result">("intro"),[countdown,setCountdown]=useState(3),[shots,setShots]=useState<PrecisionShot[]>(()=>emptyPrecisionShots(TARGETS,1)),[index,setIndex]=useState(0);
 const [carry,setCarry]=useState(TARGETS[0]),[offline,setOffline]=useState(0),[side,setSide]=useState<-1|1>(1),[compile,setCompile]=useState(0),[confirmExit,setConfirmExit]=useState(false),[analysis,setAnalysis]=useState(false),[hcpReady,setHcpReady]=useState(false); const timers=useRef<number[]>([]);
 useChipScreenColor(view==="countdown"||view==="compiling"||analysis); const filled=shots.filter(s=>s.filled),result=useMemo(()=>filled.length===9?precisionResult(shots):null,[shots,filled.length]),summary=useMemo(()=>filled.length?summarize(filled):null,[filled]);
 const sessions=typeof window==="undefined"?[]:loadPrecisionSessions(),pb=sessions.map(s=>s.score??0).reduce((a,b)=>Math.max(a,b),0); const clear=()=>{timers.current.forEach(window.clearTimeout);timers.current=[]};useEffect(()=>clear,[]);
 useEffect(()=>{if(view!=="countdown")return;setCountdown(3);const start=performance.now(),duration=2400,id=window.setInterval(()=>{const left=Math.max(0,duration-(performance.now()-start));setCountdown(left/800);if(left<=0){window.clearInterval(id);setView("test")}},40);return()=>window.clearInterval(id)},[view]);
 useEffect(()=>{if(view!=="compiling")return;setCompile(0);clear();timers.current=[window.setTimeout(()=>setCompile(1),850),window.setTimeout(()=>setCompile(2),1750),window.setTimeout(()=>setCompile(3),2650),window.setTimeout(()=>setView("result"),3400)];return clear},[view]);
 useEffect(()=>{if(!analysis)return;setHcpReady(false);const r=window.matchMedia("(prefers-reduced-motion: reduce)").matches,id=window.setTimeout(()=>setHcpReady(true),r?0:1500);return()=>window.clearTimeout(id)},[analysis]);
 function start(){const fresh=emptyPrecisionShots(TARGETS,1);setShots(fresh);setIndex(0);setCarry(TARGETS[0]);setOffline(0);setSide(1);setView("countdown")}
 function add(){const current=shots[index],nextShots=shots.map((s,i)=>i===index?{...s,carry,offline:offline*side,filled:true}:s);setShots(nextShots);if(index===8){savePrecisionSession(nextShots);setView("compiling")}else{const n=index+1;setIndex(n);setCarry(TARGETS[n]);setOffline(0);setSide(1)}}
 function undo(){if(index===0)return;const n=index-1,s=shots[n];setShots(a=>a.map((x,i)=>i===n?{...x,filled:false}:x));setIndex(n);setCarry(s.carry||s.target);setOffline(Math.abs(s.offline));setSide(s.offline<0?-1:1)}
 function abort(){clear();setConfirmExit(false);onExit()} const target=TARGETS[index],hcp=result?.handicap??null;
 return <main className="mx-auto min-h-[calc(100dvh-58px)] max-w-md bg-slate-50 px-4 pb-[max(24px,env(safe-area-inset-bottom))] pt-4 text-slate-950">
 <style>{`@keyframes aSheen{0%{transform:translateX(-140%);opacity:0}12%{opacity:1}88%{opacity:1}100%{transform:translateX(260%);opacity:0}}.a-sheen{opacity:0;animation:aSheen 1.15s ease .2s 1}@media(prefers-reduced-motion:reduce){.a-sheen{animation:none!important}}`}</style>
 {view!=="intro"&&<Button variant="ghost" aria-label="Avbryt test" onClick={()=>setConfirmExit(true)} className={`fixed left-3 top-[max(10px,env(safe-area-inset-top))] z-[130] h-11 w-11 rounded-full p-0 ${view==="countdown"||view==="compiling"?"text-white":"text-slate-700"}`}><ArrowLeft/></Button>}
 <Dialog open={confirmExit} onOpenChange={setConfirmExit}><DialogContent className="!z-[140] w-[calc(100%-32px)] max-w-sm rounded-3xl bg-white p-6"><DialogTitle className="text-2xl font-black">Avbryta testet?</DialogTitle><DialogDescription>Dina slag i det här testet sparas inte.</DialogDescription><Button onClick={abort} className="min-h-12 rounded-xl bg-slate-950 text-white">Avbryt test</Button><Button variant="outline" onClick={()=>setConfirmExit(false)} className="min-h-12 rounded-xl">Fortsätt testet</Button></DialogContent></Dialog>
 {view==="intro"?<div className="space-y-4"><section className="text-center"><p className="text-xs font-black uppercase text-blue-600">Inspel Challenge</p><h1 className="mt-1 text-4xl font-black">Hur nära slår du?</h1><p className="mx-auto mt-2 max-w-sm text-sm text-slate-600">9 slag. 9 avstånd. Ett slag från varje mål.</p></section><section className="rounded-3xl border border-blue-100 bg-white px-3 pb-5 pt-4 shadow-sm"><img src="/Approach_shot.png" alt="" className="mb-4 h-52 w-full rounded-2xl object-cover"/><div className="grid grid-cols-3 divide-x divide-slate-100 rounded-2xl bg-slate-50 py-3 text-center">{[["9 slag","55–165 m"],["HCP","Analys"],["Precision","Carry + sidled"]].map(([a,b])=><div key={a}><Check className="mx-auto mb-1 h-4 w-4 text-blue-600"/><p className="text-xs font-black">{a}</p><p className="text-[10px] text-slate-500">{b}</p></div>)}</div><Button onClick={start} className="mt-4 min-h-14 w-full rounded-2xl bg-blue-600 text-base font-black text-white">Starta Inspelstest</Button><p className="mt-3 text-center text-xs font-semibold text-slate-500">{TARGETS.join(" · ")} m</p></section>{pb>0&&<div className="flex items-center justify-between px-2 py-2"><span className="flex items-center gap-2 text-sm font-semibold"><Trophy className="h-4 w-4"/>Ditt bästa Approach Score</span><strong>{fmt(pb)}</strong></div>}</div>
 :view==="countdown"?<div className="fixed inset-0 z-[90] flex flex-col items-center justify-center bg-blue-600 px-6 text-center text-white"><p className="text-xs font-black uppercase tracking-[.18em] text-blue-100">Inspel Challenge · 9 slag</p><h1 className="mt-3 text-3xl font-black">Gör dig redo</h1><p className="mt-2 text-sm text-blue-100">Startar om {Math.max(1,Math.ceil(countdown))}</p><div className="relative mt-8 h-40 w-40"><svg className="-rotate-90 h-full w-full" viewBox="0 0 100 100"><circle cx="50" cy="50" r="40" fill="none" stroke="currentColor" strokeWidth="5" className="text-white/20"/><circle cx="50" cy="50" r="40" fill="none" stroke="currentColor" strokeWidth="5" strokeLinecap="round" strokeDasharray="251.2" strokeDashoffset={251.2*(1-Math.max(0,countdown)/3)} className="text-white"/></svg><span className="absolute inset-0 flex items-center justify-center text-6xl font-black">{Math.max(1,Math.ceil(countdown))}</span></div></div>
 :view==="test"?<div className="space-y-3"><section><p className="text-center text-xs font-semibold text-slate-500">Inspel Challenge · 9 slag</p><h1 className="mt-2 text-center text-4xl font-black">Slag {index+1}</h1><p className="mt-1 text-center text-sm font-bold text-blue-700">Mål · {target} m</p></section>{index===8&&<p className="rounded-2xl border border-violet-200 bg-violet-50 px-4 py-3 text-center font-bold text-violet-900">Sista slaget – en chans till att slå ditt rekord!</p>}<section className="rounded-3xl border border-blue-100 bg-white p-4"><label className="block text-center text-sm font-semibold text-slate-500">Carry</label><div className="my-4 flex items-baseline justify-center"><input inputMode="decimal" value={carry} onChange={e=>setCarry(Number(e.target.value)||0)} className="w-32 bg-transparent text-center text-5xl font-black text-blue-700 outline-none"/><span className="text-lg text-slate-400">m</span></div><div className="grid grid-cols-4 gap-2">{[-5,-1,1,5].map(d=><Button key={d} variant="outline" onClick={()=>setCarry(v=>Math.max(0,v+d))}>{d>0?"+":""}{d}</Button>)}</div><div className="my-4 border-t"/><label className="block text-center text-sm font-semibold text-slate-500">Sidled</label><div className="my-3 flex items-baseline justify-center"><input inputMode="decimal" value={offline} onChange={e=>setOffline(Math.max(0,Number(e.target.value)||0))} className="w-24 bg-transparent text-center text-4xl font-black outline-none"/><span className="text-sm text-slate-400">m</span></div><div className="grid grid-cols-2 gap-2">{([-1,1] as const).map(v=><Button key={v} variant={side===v?"default":"outline"} onClick={()=>setSide(v)} className={side===v?"bg-slate-600":""}>{v<0?"Vänster":"Höger"}</Button>)}</div><p className="mt-3 text-center text-xs text-slate-500">Avstånd från mål: {fmt(Math.sqrt((carry-target)**2+offline**2))} m</p><Button onClick={add} className="mt-4 min-h-14 w-full rounded-2xl bg-blue-600 text-base font-black text-white">Registrera slag</Button>{index>0&&<Button variant="ghost" onClick={undo} className="mt-1 w-full text-slate-500"><Undo2/>Ändra förra slaget</Button>}</section></div>
 :view==="compiling"?createPortal(<div className="fixed inset-0 z-[100] flex flex-col items-center justify-center bg-gradient-to-b from-blue-600 to-blue-700 p-6 text-center text-white"><span className="mb-7 flex h-16 w-16 items-center justify-center rounded-full bg-white text-blue-600">{compile>=3?<Check className="h-9 w-9"/>:<LoaderCircle className="h-9 w-9 motion-safe:animate-spin"/>}</span><h1 className="text-3xl font-black">{compile>=3?"Resultatet klart":"Sammanställer testet…"}</h1><div className="mt-6 w-full max-w-xs space-y-4 text-left text-blue-100">{["Sammanställer dina nio slag","Beräknar din precision","Förbereder din HCP-analys"].map((x,i)=><p key={x} className={`flex items-center gap-3 ${i<=compile?"opacity-100":"opacity-0"}`}>{i<compile||compile>=3?<Check className="h-5 w-5"/>:<LoaderCircle className="h-5 w-5 motion-safe:animate-spin"/>}{x}</p>)}</div></div>,document.body)
 :result&&summary?<div className="space-y-4"><section className="relative overflow-hidden rounded-3xl border border-blue-100 bg-white p-5 text-center shadow-sm"><span className="a-sheen pointer-events-none absolute inset-y-0 w-20 -skew-x-12 bg-gradient-to-r from-transparent via-blue-100/80 to-transparent"/><p className="text-xs font-black uppercase text-blue-600">Ditt resultat</p><h1 className="mt-1 text-2xl font-black">Inspelstest klart</h1><p className="mt-4 text-5xl font-black text-blue-700">{fmt(summary.avgProximity)} m</p><p className="text-sm text-slate-500">Snittavstånd från målet</p><div className="mt-5 rounded-2xl bg-slate-50 p-5"><p className="text-sm font-semibold text-slate-500">Median</p><p className="mt-2 text-3xl font-bold text-slate-600">{fmt(summary.medianProximity)} m</p></div></section><Button onClick={()=>setAnalysis(true)} className="min-h-14 w-full rounded-2xl bg-blue-600 text-base font-black text-white">Visa min HCP-analys</Button><Button onClick={start} className="min-h-14 w-full rounded-2xl bg-slate-950 text-white"><RotateCcw/>Testa igen · 9 slag</Button></div>:null}
 <Dialog open={analysis} onOpenChange={setAnalysis}><DialogContent className="!fixed !inset-0 !h-[100dvh] !max-h-none !w-full !max-w-none !translate-x-0 !translate-y-0 !rounded-none !border-0 !bg-blue-600 !p-0 text-white [&>button]:text-white"><DialogTitle className="sr-only">Approach HCP-analys</DialogTitle><DialogDescription className="sr-only">Ditt estimerade Approach-HCP.</DialogDescription><div className="flex h-full flex-col items-center justify-center px-6 text-center"><p className="text-sm font-bold uppercase tracking-widest text-blue-100">Inspel HCP-analys</p><h2 className="mt-5 text-3xl font-black">{hcpReady?"Ditt Approach-HCP":"Analyserar dina nio slag…"}</h2><div className="my-8 text-[clamp(88px,27vw,132px)] font-black">{hcpReady&&hcp!==null?handicapLabel(hcp):<LoaderCircle className="mx-auto h-16 w-16 motion-safe:animate-spin"/>}</div>{hcpReady&&summary&&<div className="w-full max-w-xs rounded-3xl bg-white/10 p-5 text-left"><p className="flex justify-between"><span>Snittavstånd</span><strong>{fmt(summary.avgProximity)} m</strong></p><p className="mt-3 flex justify-between"><span>Median</span><strong>{fmt(summary.medianProximity)} m</strong></p></div>}<Button onClick={()=>setAnalysis(false)} className="mt-7 min-h-14 w-full max-w-xs rounded-full bg-white font-black text-blue-700">Till resultatet</Button></div></DialogContent></Dialog>
 </main>
}