import { createPortal } from "react-dom";
import { useEffect,useMemo,useRef,useState } from "react";
import { ArrowLeft,Check,LoaderCircle,RotateCcw,Star,Undo2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Dialog,DialogContent,DialogDescription,DialogTitle } from "@/components/ui/dialog";
import { CHIP_ZONES,type ChipPoints } from "@/lib/chip-stations";
import { courseHandicap,holeStars,roundStars,type CourseRound } from "@/lib/chip-course";
import { handicapLabel } from "@/lib/shortgame";
import { useChipScreenColor } from "@/lib/use-chip-screen-color";
const DIST=[8,12,18],fmt=(n:number)=>n.toFixed(1).replace(".",",");
export function NineShotChipTest({onExit}:{onExit:()=>void}){
 const [view,setView]=useState<"intro"|"countdown"|"test"|"compiling"|"result">("intro"),[countdown,setCountdown]=useState(3),[station,setStation]=useState(0),[balls,setBalls]=useState<ChipPoints[][]>([[],[],[]]),[compile,setCompile]=useState(0),[confirmExit,setConfirmExit]=useState(false),[analysis,setAnalysis]=useState(false),[hcpReady,setHcpReady]=useState(false);const timers=useRef<number[]>([]);
 useChipScreenColor(view==="countdown"||view==="compiling"||analysis);const done=balls.reduce((a,b)=>a+b.length,0),current=balls[station],stars=balls.reduce((sum,b,i)=>sum+holeStars(b,i,"Fairway",4),0);
 const round=useMemo<CourseRound|null>(()=>done===9?{id:"chip-3x3",model:4,lie:"Fairway",startedAt:0,finishedAt:Date.now(),holes:balls,status:"front",distances:DIST}:null,[done,balls]);const hcp=round?courseHandicap(round):null;
 const clear=()=>{timers.current.forEach(window.clearTimeout);timers.current=[]};useEffect(()=>clear,[]);
 useEffect(()=>{if(view!=="countdown")return;setCountdown(3);const start=performance.now(),duration=2400,id=window.setInterval(()=>{const left=Math.max(0,duration-(performance.now()-start));setCountdown(left/800);if(left<=0){window.clearInterval(id);setView("test")}},40);return()=>window.clearInterval(id)},[view]);
 useEffect(()=>{if(view!=="compiling")return;setCompile(0);clear();timers.current=[window.setTimeout(()=>setCompile(1),850),window.setTimeout(()=>setCompile(2),1750),window.setTimeout(()=>setCompile(3),2650),window.setTimeout(()=>setView("result"),3400)];return clear},[view]);
 useEffect(()=>{if(!analysis)return;setHcpReady(false);const r=window.matchMedia("(prefers-reduced-motion: reduce)").matches,id=window.setTimeout(()=>setHcpReady(true),r?0:1500);return()=>window.clearTimeout(id)},[analysis]);
 function start(){setBalls([[],[],[]]);setStation(0);setView("countdown")}function score(p:ChipPoints){const next=balls.map((b,i)=>i===station?[...b,p]:b);setBalls(next);if(next[station].length===3){if(station===2)setView("compiling");else setStation(station+1)}}function undo(){if(current.length)setBalls(a=>a.map((b,i)=>i===station?b.slice(0,-1):b));else if(station>0){setStation(station-1);setBalls(a=>a.map((b,i)=>i===station-1?b.slice(0,-1):b))}}function abort(){clear();setConfirmExit(false);onExit()}
 return <main className="mx-auto min-h-[calc(100dvh-58px)] max-w-md bg-slate-50 px-4 pb-[max(24px,env(safe-area-inset-bottom))] pt-4 text-slate-950">
 {view!=="intro"&&<Button variant="ghost" aria-label="Avbryt test" onClick={()=>setConfirmExit(true)} className={`fixed left-3 top-[max(10px,env(safe-area-inset-top))] z-[130] h-11 w-11 rounded-full p-0 ${view==="countdown"||view==="compiling"?"text-white":"text-slate-700"}`}><ArrowLeft/></Button>}
 <Dialog open={confirmExit} onOpenChange={setConfirmExit}><DialogContent className="!z-[140] w-[calc(100%-32px)] max-w-sm rounded-3xl bg-white p-6"><DialogTitle className="text-2xl font-black">Avbryta testet?</DialogTitle><DialogDescription>Dina slag i det här testet sparas inte.</DialogDescription><Button onClick={abort} className="min-h-12 bg-slate-950 text-white">Avbryt test</Button><Button variant="outline" onClick={()=>setConfirmExit(false)}>Fortsätt testet</Button></DialogContent></Dialog>
 {view==="intro"?<div className="space-y-4"><section className="text-center"><p className="text-xs font-black uppercase text-blue-600">Chipping Challenge</p><h1 className="mt-1 text-4xl font-black">Hur nära chippar du?</h1><p className="mt-2 text-sm text-slate-600">3 stationer. 3 bollar per station. Samla stjärnor och få ditt chipp-HCP.</p></section><section className="rounded-3xl border border-blue-100 bg-white p-4 shadow-sm"><img src="/0d286fd4-99fa-47eb-b39c-a7ff718ebdd6.png" alt="" className="mb-4 h-52 w-full rounded-2xl object-cover"/><div className="grid grid-cols-3 divide-x rounded-2xl bg-slate-50 py-3 text-center">{DIST.map(d=><div key={d}><strong className="text-lg">{d} m</strong><p className="text-[10px] text-slate-500">3 bollar</p></div>)}</div><Button onClick={start} className="mt-4 min-h-14 w-full rounded-2xl bg-blue-600 text-base font-black text-white">Starta Chipping-Test</Button></section></div>
 :view==="countdown"?<div className="fixed inset-0 z-[90] flex flex-col items-center justify-center bg-blue-600 text-center text-white"><p className="text-xs font-black uppercase tracking-[.18em] text-blue-100">Chipping Challenge · 9 slag</p><h1 className="mt-3 text-3xl font-black">Gör dig redo</h1><p className="mt-2 text-blue-100">Startar om {Math.max(1,Math.ceil(countdown))}</p><div className="relative mt-8 h-40 w-40"><svg className="-rotate-90 h-full w-full" viewBox="0 0 100 100"><circle cx="50" cy="50" r="40" fill="none" stroke="currentColor" strokeWidth="5" className="text-white/20"/><circle cx="50" cy="50" r="40" fill="none" stroke="currentColor" strokeWidth="5" strokeLinecap="round" strokeDasharray="251.2" strokeDashoffset={251.2*(1-Math.max(0,countdown)/3)} className="text-white"/></svg><span className="absolute inset-0 flex items-center justify-center text-6xl font-black">{Math.max(1,Math.ceil(countdown))}</span></div></div>
 :view==="test"?<div className="space-y-4"><section className="text-center"><p className="text-xs font-semibold text-slate-500">Chipping Challenge · Station {station+1} av 3</p><h1 className="mt-2 text-5xl font-black text-blue-700">{DIST[station]} m</h1><p className="mt-1 font-bold">Boll {current.length+1} av 3</p><div className="mt-3 flex justify-center gap-1">{[0,1,2].map(i=><Star key={i} className={`h-7 w-7 ${i<Math.floor(holeStars(current,station,"Fairway",4))?"fill-amber-400 text-amber-400":"text-slate-200"}`}/>)}</div><p className="mt-1 text-xs text-slate-500">{fmt(holeStars(current,station,"Fairway",4))} / 3 ★</p></section>{done===8&&<p className="rounded-2xl border border-violet-200 bg-violet-50 px-4 py-3 text-center font-bold text-violet-900">Sista bollen – en chans till att slå ditt rekord!</p>}<section className="rounded-3xl border border-blue-100 bg-white p-4"><p className="mb-3 text-center text-sm font-semibold text-slate-500">Hur nära hålet?</p><div className="grid gap-2">{CHIP_ZONES.map(z=><Button key={z.points} variant="outline" onClick={()=>score(z.points)} className="min-h-14 justify-between rounded-2xl px-4"><span className="font-bold">{z.label}</span><span className="text-slate-400">+{z.points}</span></Button>)}</div>{done>0&&<Button variant="ghost" onClick={undo} className="mt-2 w-full text-slate-500"><Undo2/>Ändra förra bollen</Button>}</section></div>
 :view==="compiling"?createPortal(<div className="fixed inset-0 z-[100] flex flex-col items-center justify-center bg-blue-600 p-6 text-center text-white"><span className="mb-7 flex h-16 w-16 items-center justify-center rounded-full bg-white text-blue-600">{compile>=3?<Check className="h-9 w-9"/>:<LoaderCircle className="h-9 w-9 motion-safe:animate-spin"/>}</span><h1 className="text-3xl font-black">{compile>=3?"Resultatet klart":"Sammanställer testet…"}</h1><div className="mt-6 space-y-4 text-left text-blue-100">{["Sammanställer dina nio chippar","Räknar dina stjärnor","Förbereder din HCP-analys"].map((x,i)=><p key={x} className={`flex gap-3 ${i<=compile?"opacity-100":"opacity-0"}`}>{i<compile||compile>=3?<Check/>:<LoaderCircle className="motion-safe:animate-spin"/>}{x}</p>)}</div></div>,document.body)
 :view==="result"&&round?<div className="space-y-4"><section className="rounded-3xl border border-blue-100 bg-white p-5 text-center"><p className="text-xs font-black uppercase text-blue-600">Ditt resultat</p><h1 className="mt-1 text-2xl font-black">Chipping-Test klart</h1><p className="mt-4 text-5xl font-black text-amber-500">{fmt(stars)} ★</p><p className="text-sm text-slate-500">av 9 stjärnor</p><div className="mt-5 grid grid-cols-3 gap-2">{balls.map((b,i)=><div key={DIST[i]} className="rounded-2xl bg-slate-50 p-3"><strong>{DIST[i]} m</strong><p className="mt-1 text-lg font-black text-amber-500">{fmt(holeStars(b,i,"Fairway",4))} ★</p></div>)}</div></section><Button onClick={()=>setAnalysis(true)} className="min-h-14 w-full rounded-2xl bg-blue-600 font-black text-white">Visa min HCP-analys</Button><Button onClick={start} className="min-h-14 w-full rounded-2xl bg-slate-950 text-white"><RotateCcw/>Testa igen · 9 slag</Button></div>:null}
 <Dialog open={analysis} onOpenChange={setAnalysis}><DialogContent className="!fixed !inset-0 !h-[100dvh] !max-h-none !w-full !max-w-none !translate-x-0 !translate-y-0 !rounded-none !border-0 !bg-blue-600 !p-0 text-white [&>button]:text-white"><DialogTitle className="sr-only">Chipp HCP-analys</DialogTitle><DialogDescription className="sr-only">Ditt estimerade chipp-handicap.</DialogDescription><div className="flex h-full flex-col items-center justify-center px-6 text-center"><p className="text-sm font-bold uppercase tracking-widest text-blue-100">Chipp HCP-analys</p><h2 className="mt-5 text-3xl font-black">{hcpReady?"Ditt estimerade HCP":"Analyserar dina nio chippar…"}</h2><div className="my-8 text-[clamp(88px,27vw,132px)] font-black">{hcpReady&&hcp!==null?handicapLabel(hcp):<LoaderCircle className="mx-auto h-16 w-16 motion-safe:animate-spin"/>}</div>{hcpReady&&<div className="w-full max-w-xs rounded-3xl bg-white/10 p-5"><p className="text-sm text-blue-100">Stjärnor</p><strong className="mt-1 block text-3xl">{fmt(roundStars(round))} / 9 ★</strong></div>}<Button onClick={()=>setAnalysis(false)} className="mt-7 min-h-14 w-full max-w-xs rounded-full bg-white font-black text-blue-700">Till resultatet</Button></div></DialogContent></Dialog>
 </main>
}