import { Link } from "@tanstack/react-router";
import { ArrowLeft, Target, Trophy } from "lucide-react";
import { Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { useState } from "react";

type Kind = "wedge" | "iron";
type Session = { id: string; date: string; pei: number };
const CFG = { wedge: { title: "Wedge PEI", key: "sg4-pei-wedge-v1", back: "/approach-pei-wedge" as const }, iron: { title: "Iron PEI", key: "sg4-pei-iron-v1", back: "/approach-pei-iron" as const } };
function load(key:string):Session[]{if(typeof window==="undefined")return[];try{return JSON.parse(localStorage.getItem(key)||"[]")}catch{return[]}}
export function PeiFocusHistory({kind}:{kind:Kind}){const cfg=CFG[kind];const[sessions]=useState(()=>load(cfg.key));const best=sessions.length?Math.min(...sessions.map(s=>s.pei)):null;const latest=sessions.at(-1)?.pei??null;const data=sessions.map((s,i)=>({n:i+1,pei:Number(s.pei.toFixed(2))}));return <main className="mx-auto min-h-screen w-full max-w-md px-6 pb-16 pt-6"><Link to={cfg.back} className="inline-flex h-10 w-10 items-center justify-center rounded-full border border-border"><ArrowLeft className="h-4 w-4"/></Link><p className="mt-6 text-xs uppercase tracking-[0.22em] text-muted-foreground">Approach · {cfg.title}</p><h1 className="mt-1 text-4xl">Resultat över tid</h1>{sessions.length?<><div className="mt-5 grid grid-cols-2 gap-3"><div className="rounded-2xl border border-border bg-card p-4"><Trophy className="h-4 w-4 text-primary"/><p className="mt-2 text-xs text-muted-foreground">PB</p><p className="font-display text-3xl">{best?.toFixed(2)}%</p></div><div className="rounded-2xl border border-border bg-card p-4"><Target className="h-4 w-4 text-primary"/><p className="mt-2 text-xs text-muted-foreground">Senast</p><p className="font-display text-3xl">{latest?.toFixed(2)}%</p></div></div><section className="mt-5 rounded-3xl border border-border bg-card p-4"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-muted-foreground">PEI-utveckling</p><div className="mt-4 h-64"><ResponsiveContainer width="100%" height="100%"><LineChart data={data} margin={{top:8,right:8,left:-16,bottom:0}}><XAxis dataKey="n" tickLine={false} axisLine={false}/><YAxis tickLine={false} axisLine={false} domain={["auto","auto"]}/><Tooltip formatter={(v)=>[`${Number(v).toFixed(2)}%`,"PEI"]}/><Line type="monotone" dataKey="pei" stroke="currentColor" strokeWidth={2.5} dot={{r:3}}/></LineChart></ResponsiveContainer></div></section></>:<div className="mt-8 rounded-3xl border border-dashed border-border p-8 text-center"><p className="text-sm text-muted-foreground">Genomför ditt första {cfg.title}-test så visas utvecklingen här.</p></div>}</main>}
