import { useMemo, useState } from "react";
import { PolarAngleAxis, PolarGrid, PolarRadiusAxis, Radar, RadarChart, ResponsiveContainer, Tooltip } from "recharts";
import { collectLagHoleOutStarts, collectPuttStarts, puttingMakeStats } from "@/lib/putting-global";

const BLUE="var(--chart-4)"; const RED="var(--chart-3)";
type Key="0-1"|"1-2"|"2-3"|"3-5"|"three-putt";
type B={label:string;skillScore:number;values:Record<Key,number>};
const BMS:B[]=[
 {label:"PGA Tour",skillScore:100,values:{"0-1":99,"1-2":82,"2-3":50,"3-5":30,"three-putt":97.5}},
 {label:"HCP 0",skillScore:85,values:{"0-1":98,"1-2":76,"2-3":49,"3-5":34,"three-putt":92.2}},
 {label:"HCP 10",skillScore:65,values:{"0-1":96,"1-2":65,"2-3":39,"3-5":26,"three-putt":88.2}},
 {label:"HCP 20",skillScore:45,values:{"0-1":90,"1-2":55,"2-3":33,"3-5":18,"three-putt":80.9}},
];
const clamp=(v:number)=>Math.max(0,Math.min(100,v));
function skill(k:Key,raw:number){const a=BMS.map(b=>({raw:b.values[k],score:b.skillScore})).sort((x,y)=>x.raw-y.raw);if(raw>=a.at(-1)!.raw)return 100;if(raw<=a[0].raw)return clamp(raw/Math.max(1,a[0].raw)*a[0].score);for(let i=0;i<a.length-1;i++){if(raw>=a[i].raw&&raw<=a[i+1].raw){const t=(raw-a[i].raw)/(a[i+1].raw-a[i].raw||1);return clamp(a[i].score+t*(a[i+1].score-a[i].score))}}return 0}
function bin(rows:ReturnType<typeof puttingMakeStats>,min:number,max:number,first=false){const r=rows.filter(x=>first?x.distance>=min&&x.distance<=max:x.distance>min&&x.distance<=max);const attempts=r.reduce((s,x)=>s+x.attempts,0),made=r.reduce((s,x)=>s+x.made,0);return{attempts,pct:attempts?made/attempts*100:0}}
function Tip({active,payload}:{active?:boolean;payload?:Array<{payload?:any}>}){if(!active||!payload?.length)return null;const r=payload[0].payload;return <div className="rounded-xl border border-border bg-card px-3 py-2 text-xs shadow-lg"><p className="font-semibold">{r.subject}</p><p className="mt-1 text-muted-foreground">Du: <span className="font-semibold text-foreground">{Math.round(r.raw)}%</span></p><p className="text-muted-foreground">{r.label}: <span className="font-semibold text-foreground">{Math.round(r.benchmarkRaw)}%</span></p></div>}
export function PuttingRadarAnalysis(){const[target,setTarget]=useState(BMS[2]);const starts=useMemo(()=>collectPuttStarts(),[]);const lag=useMemo(()=>collectLagHoleOutStarts(),[]);const stats=puttingMakeStats(starts);if(!starts.length)return <div className="flex h-80 items-center justify-center rounded-3xl border border-border bg-card text-sm text-muted-foreground">Registrera puttar för att bygga analysen.</div>;const a=bin(stats,0,1,true),b=bin(stats,1,2),c=bin(stats,2,3),d=bin(stats,3,5);const avoid=lag.length?100-lag.filter(x=>x.strokes>=3).length/lag.length*100:0;const raw=[{key:"0-1" as Key,subject:"0–1 m",raw:a.pct,attempts:a.attempts},{key:"1-2" as Key,subject:"1–2 m",raw:b.pct,attempts:b.attempts},{key:"2-3" as Key,subject:"2–3 m",raw:c.pct,attempts:c.attempts},{key:"3-5" as Key,subject:"3–5 m",raw:d.pct,attempts:d.attempts},{key:"three-putt" as Key,subject:"3-putt undvik.",raw:avoid,attempts:lag.length}];const data=raw.map(r=>({...r,value:skill(r.key,r.raw),benchmark:target.skillScore,benchmarkRaw:target.values[r.key],label:target.label}));return <div><div className="flex gap-2 overflow-x-auto pb-1">{BMS.map(bm=><button key={bm.label} type="button" onClick={()=>setTarget(bm)} className={`shrink-0 rounded-full border px-3 py-1.5 text-xs font-semibold ${target.label===bm.label?"border-chart-3 bg-chart-3/10 text-chart-3":"border-border text-muted-foreground"}`}>{bm.label}</button>)}</div><div className="mt-2 h-80 w-full"><ResponsiveContainer width="100%" height="100%"><RadarChart data={data} outerRadius="68%"><PolarGrid stroke="var(--border)"/><PolarAngleAxis dataKey="subject" tick={{fontSize:10,fill:"var(--muted-foreground)"}}/><PolarRadiusAxis domain={[0,110]} tick={false} axisLine={false}/><Radar dataKey="benchmark" stroke={RED} fill={RED} fillOpacity={.12} strokeWidth={2}/><Radar dataKey="value" stroke={BLUE} fill={BLUE} fillOpacity={.28} strokeWidth={2.5} dot={{r:3,fill:BLUE}}/><Tooltip content={<Tip/>}/></RadarChart></ResponsiveContainer></div><div className="flex items-center justify-center gap-5 text-[11px] text-muted-foreground"><span className="inline-flex items-center gap-1.5"><span className="h-2.5 w-2.5 rounded-full bg-chart-4"/>Du</span><span className="inline-flex items-center gap-1.5"><span className="h-2.5 w-2.5 rounded-full bg-chart-3"/>{target.label}</span></div></div>}
