import { useEffect,useState,type ReactNode } from "react";
import { ArrowLeft,ArrowRight } from "lucide-react";
import { Button } from "@/components/ui/button";
import { ChipCelebration } from "@/components/chip-celebration";
import { handicapLabel } from "@/lib/shortgame";
export type HcpAnalysisSlide={key:string;content:ReactNode};
export const performanceGrade=(value:number,thresholds={exceptionell:0,briljant:5,bra:12,forvantat:22,svag:32})=>value<=thresholds.exceptionell?"exceptionell":value<=thresholds.briljant?"briljant":value<=thresholds.bra?"bra":value<=thresholds.forvantat?"förväntat":value<=thresholds.svag?"svag":"stort tapp";
export function StandardHcpAnalysis({title,hcp,slides,onClose}:{title:string;hcp:number;slides:HcpAnalysisSlide[];onClose:()=>void}){
 const [page,setPage]=useState(0),[display,setDisplay]=useState(40),[ready,setReady]=useState(false);
 useEffect(()=>{setPage(0);setDisplay(40);setReady(false);const reduced=window.matchMedia("(prefers-reduced-motion: reduce)").matches;if(reduced){setDisplay(hcp);setReady(true);return}const start=performance.now(),duration=2600;let raf=0;const tick=(now:number)=>{const p=Math.min(1,(now-start)/duration),e=1-Math.pow(1-p,4);setDisplay(40+(hcp-40)*e);if(p<1)raf=requestAnimationFrame(tick);else setReady(true)};raf=requestAnimationFrame(tick);return()=>cancelAnimationFrame(raf)},[hcp]);
 const all=[{key:"hcp",content:<section className="text-center">{ready&&<ChipCelebration confettiOnly/>}<p className="text-sm font-bold uppercase tracking-widest text-blue-100">{title}</p><h2 className="mt-4 text-3xl font-black">Ditt estimerade HCP</h2><div className="my-8 text-[clamp(88px,27vw,132px)] font-black tabular-nums">{handicapLabel(Math.round(display*10)/10)}</div></section>},...slides];
 const last=page===all.length-1;
 return <div className="mx-auto flex h-full min-h-0 w-full max-w-md flex-col px-5 pb-[max(20px,env(safe-area-inset-bottom))] pt-[max(70px,calc(env(safe-area-inset-top)+60px))]"><div className="mb-2 flex shrink-0 justify-center gap-1.5" aria-label={`Sida ${page+1} av ${all.length}`}>{all.map((x,i)=><span key={x.key} className={`h-1.5 rounded-full transition-all duration-300 ${i===page?"w-6 bg-white":"w-1.5 bg-white/35"}`}/>)}</div><div className={`flex min-h-0 flex-1 flex-col overflow-y-auto py-4 ${all[page].key==="shots"?"justify-start":"justify-center"}`}>{all[page].content}</div><nav className="mt-4 flex shrink-0 gap-3">{page>0&&<Button onClick={()=>setPage(p=>p-1)} className="h-14 w-14 rounded-full border border-white/30 bg-transparent text-white hover:bg-white/10"><ArrowLeft/></Button>}<Button disabled={page===0&&!ready} onClick={()=>last?onClose():setPage(p=>p+1)} className="min-h-14 flex-1 rounded-full bg-white font-bold text-blue-700 hover:bg-white">{last?"Se testresultatet":<>Nästa <ArrowRight className="ml-2 h-4 w-4"/></>}</Button></nav></div>
}
export function ShotAnalysisList({title,rows,showSummary=false}:{title:string;rows:{label:string;value:string;grade:"exceptionell"|"briljant"|"bra"|"förväntat"|"godkänt"|"svag"|"svagt"|"stort tapp"}[];showSummary?:boolean}){
 const displayGrade=(g:string)=>g==="förväntat"?"godkänt":g==="svag"?"svagt":g;
 const cls=(g:string)=>{const grade=displayGrade(g);return grade==="exceptionell"?"text-emerald-200":grade==="briljant"?"text-emerald-300":grade==="bra"?"text-lime-200":grade==="godkänt"?"text-amber-200":grade==="svagt"?"text-slate-300":"text-slate-400"};
 const grades=["exceptionell","briljant","bra","godkänt","svagt","stort tapp"] as const;
 const counts=grades.map(grade=>({grade,count:rows.filter(row=>displayGrade(row.grade)===grade).length}));
 return <section className="w-full pb-4"><p className="text-[11px] font-bold uppercase tracking-widest text-blue-100">{title}</p>{showSummary?<div className="mt-3 overflow-hidden rounded-2xl bg-white/10">{counts.map(({grade,count},index)=><div key={grade} className={`flex min-h-10 items-center justify-between px-4 ${index<counts.length-1?"border-b border-white/10":""}`}><span className={`text-[12px] font-bold capitalize ${cls(grade)}`}>{grade}</span><strong className={`text-xl font-black ${cls(grade)}`}>{count}</strong></div>)}</div>:null}<h2 className="mt-7 text-2xl font-black">Slag för slag</h2><div className="mt-3 space-y-2">{rows.map((r,i)=><div key={i} className="flex min-h-[58px] items-center justify-between gap-3 rounded-2xl bg-white/10 px-4 py-3 text-left"><div className="min-w-0"><p className="text-[13px] font-bold">{r.label}</p><p className="mt-0.5 text-[12px] text-blue-100">{r.value}</p></div><strong className={`shrink-0 text-[12px] font-bold capitalize ${cls(r.grade)}`}>{displayGrade(r.grade)}</strong></div>)}</div></section>
}

export function BenchmarkStory({title,hcp,tourLabel,tourValue}:{title:string;hcp:number;tourLabel:string;tourValue:string}){return <section className="text-center"><p className="text-sm font-bold uppercase tracking-widest text-blue-100">Jämförelse</p><h2 className="mt-4 text-3xl font-black">{title}</h2><div className="mt-6 grid grid-cols-2 gap-3"><div className="rounded-3xl bg-white p-5 text-blue-700"><p className="text-sm font-semibold">Din nivå</p><p className="mt-3 text-4xl font-black">{handicapLabel(hcp)}</p></div><div className="rounded-3xl bg-white/10 p-5"><p className="text-sm font-semibold">{tourLabel}</p><p className="mt-3 text-3xl font-black">{tourValue}</p></div></div><p className="mt-5 text-sm text-blue-100">Tourvärdet är en referenspunkt för testets relevanta egenskap.</p></section>}
