import { createPortal } from "react-dom";
import { useEffect, useMemo, useRef, useState } from "react";
import { ArrowLeft, ArrowRight, Check, LoaderCircle, RotateCcw, Trophy, Undo2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogTitle } from "@/components/ui/dialog";
import { offTeeResult, type TeeShot } from "@/lib/offtee";
import { handicapLabel } from "@/lib/shortgame";
import { loadLongDriveSessions, saveLongDriveSession, sessionBest, todayISO } from "@/lib/longdrive";
import { useChipScreenColor } from "@/lib/use-chip-screen-color";
import { ChipCelebration } from "@/components/chip-celebration";
import { DrivingHcpBellCurve } from "@/components/offtee-bellcurve";
import { ShotAnalysisList } from "@/components/standard-hcp-analysis";
import { HcpComparisonBellCurve } from "@/components/hcp-comparison-bellcurve";
import { loadCardProfile } from "@/lib/rating-card";
import { TOUR } from "@/lib/benchmarks";
type Mode="longdrive"|"offtee"; type Shot={distance:number;lateral:number;side:"left"|"right"|"center"}; type Saved={id:string;at:number;shots:Shot[]};
const KEY="sg4-offtee-three-shot-v1",fmt=(n:number)=>n.toFixed(1).replace(".",",");
const tee=(a:Shot[]):TeeShot[]=>a.map((s,i)=>({index:i+1,filled:true,total:s.distance,sidled:s.lateral,direction:s.side==="left"?"left":"right"}));
function loadOfftee():Saved[]{try{const v=JSON.parse(localStorage.getItem(KEY)??"[]");return Array.isArray(v)?v:[]}catch{return[]}}
function saveOfftee(x:Saved){localStorage.setItem(KEY,JSON.stringify([...loadOfftee(),x].slice(-30)))}
function LongDriveLeaderboard({sessions}:{sessions:ReturnType<typeof loadLongDriveSessions>}){const recent=sessions.slice(-5),average=recent.length?recent.reduce((sum,x)=>sum+sessionBest(x),0)/recent.length:0;return <section className="mt-5 overflow-hidden rounded-3xl border border-blue-100 bg-white"><div className="border-b border-blue-100 p-5"><h2 className="flex items-center gap-2 text-lg font-black"><Trophy className="h-5 w-5"/>Topplista</h2><p className="mt-1 text-sm text-slate-500">Baserat på längsta totallängd · senaste 5 tester</p></div><div className="flex justify-between px-4 pt-3 text-xs font-bold uppercase text-slate-400"><span>Spelare</span><span>Snitt</span></div><div className="flex items-center justify-between px-4 py-4"><span className="font-bold">1&nbsp;&nbsp; Du</span><strong>{recent.length?fmt(average)+" m":"–"}</strong></div><div className="px-4 pb-4 text-sm font-bold text-blue-600">Hitta och lägg till vänner →</div></section>}
export function ThreeShotDriverTest({mode,onExit}:{mode:Mode;onExit:()=>void}){
 const long=mode==="longdrive",title=long?"Long Drive":"Utslag";
 const [view,setView]=useState<"intro"|"countdown"|"test"|"compiling"|"result">("intro"),[countdown,setCountdown]=useState(3),[shots,setShots]=useState<Shot[]>([]);
 const [distance,setDistance]=useState(long?"250":"220"),[lateral,setLateral]=useState("0"),[side,setSide]=useState<"left"|"right"|null>(null),[compile,setCompile]=useState(0);
 const [distanceTouched,setDistanceTouched]=useState(false),[lateralTouched,setLateralTouched]=useState(false),[registeredShot,setRegisteredShot]=useState<{shot:Shot;index:number}|null>(null);
 const [confirmExit,setConfirmExit]=useState(false),[analysis,setAnalysis]=useState(false),[hcpReady,setHcpReady]=useState(false),[analysisPage,setAnalysisPage]=useState(0),[rollingHcp,setRollingHcp]=useState(40); const age=typeof window==="undefined"?undefined:loadCardProfile().age; const timers=useRef<number[]>([]);
 useChipScreenColor(view==="countdown"||view==="compiling"||analysis);
 useEffect(()=>{document.documentElement.dataset.sg4TestActive=view==="intro"?"false":"true";return()=>{delete document.documentElement.dataset.sg4TestActive}},[view]);
 useEffect(()=>{const handler=()=>setConfirmExit(true);window.addEventListener("sg4-test-abort",handler);return()=>window.removeEventListener("sg4-test-abort",handler)},[]);
 const result=useMemo(()=>shots.length===3?offTeeResult(tee(shots)):null,[shots]),best=Math.max(0,...shots.map(s=>s.distance)),avg=shots.length?shots.reduce((a,s)=>a+s.distance,0)/shots.length:0;
 const longSessions=typeof window==="undefined"?[]:loadLongDriveSessions(); const pb=long?Math.max(0,...longSessions.map(sessionBest)):typeof window==="undefined"?0:Math.max(0,...loadOfftee().flatMap(t=>t.shots.map(s=>s.distance)));
 const clear=()=>{timers.current.forEach(window.clearTimeout);timers.current=[]}; useEffect(()=>clear,[]);
 useEffect(()=>{if(view!=="countdown")return;setCountdown(3);const start=performance.now(),duration=2400,id=window.setInterval(()=>{const left=Math.max(0,duration-(performance.now()-start));setCountdown(left/800);if(left<=0){window.clearInterval(id);setView("test")}},40);return()=>window.clearInterval(id)},[view]);
 useEffect(()=>{if(view!=="compiling")return;setCompile(0);clear();timers.current=[window.setTimeout(()=>setCompile(1),850),window.setTimeout(()=>setCompile(2),1750),window.setTimeout(()=>setCompile(3),2650),window.setTimeout(()=>setView("result"),3400)];return clear},[view]);
 useEffect(()=>{if(!analysis)return;setHcpReady(false);setAnalysisPage(0);setRollingHcp(40);const r=window.matchMedia("(prefers-reduced-motion: reduce)").matches;if(r){setRollingHcp(result?.handicap??0);setHcpReady(true);return}const start=performance.now(),duration=2600;let raf=0;const tick=(now:number)=>{const p=Math.min(1,(now-start)/duration),e=1-Math.pow(1-p,4);setRollingHcp(40+((result?.handicap??0)-40)*e);if(p<1)raf=requestAnimationFrame(tick);else setHcpReady(true)};raf=requestAnimationFrame(tick);return()=>cancelAnimationFrame(raf)},[analysis,result]);
 function start(){setShots([]);setDistance(long?"250":"220");setLateral("0");setSide(null);setDistanceTouched(false);setLateralTouched(false);setRegisteredShot(null);setView("countdown")}
 function add(){const d=Number(distance.replace(",",".")),l=long?0:Number(lateral.replace(",","."));if(!Number.isFinite(d)||d<=0||d>400||!Number.isFinite(l)||l<0||l>200||(!long&&l>0&&!side))return;const shot={distance:d,lateral:l,side:l===0?"center":side!} as Shot,next=[...shots,shot];setShots(next);setRegisteredShot({shot,index:next.length});if(next.length===3){if(long)saveLongDriveSession({date:todayISO(),carries:next.map(s=>s.distance),unit:"m"});else saveOfftee({id:crypto.randomUUID(),at:Date.now(),shots:next})}}
 function continueAfterRegistration(){const finished=shots.length===3;setRegisteredShot(null);if(finished){setView("compiling");return}setLateral("0");setSide(null);setLateralTouched(false)}
 function abort(){clear();setConfirmExit(false);setShots([]);onExit()} const shotNo=Math.min(3,shots.length+1),hcp=result?.handicap??null;
 return <main className="mx-auto min-h-[calc(100dvh-58px)] max-w-md bg-slate-50 px-4 pb-[max(24px,env(safe-area-inset-bottom))] pt-4 text-slate-950">
 <div className="fixed left-1/2 top-[max(70px,calc(env(safe-area-inset-top)+62px))] z-[150] -translate-x-1/2"></div><style>{`@keyframes dSheen{0%{transform:translateX(-140%);opacity:0}12%{opacity:1}88%{opacity:1}100%{transform:translateX(260%);opacity:0}}.d-sheen{opacity:0;animation:dSheen 1.15s ease .2s 1}@media(prefers-reduced-motion:reduce){.d-sheen{animation:none!important}}`}</style>
 <Dialog open={confirmExit} onOpenChange={setConfirmExit}><DialogContent className="!z-[140] w-[calc(100%-32px)] max-w-sm rounded-3xl bg-white p-6"><DialogTitle className="text-2xl font-black">Avbryta testet?</DialogTitle><DialogDescription>Dina slag i det här testet sparas inte.</DialogDescription><Button onClick={abort} className="min-h-12 rounded-xl bg-slate-950 text-white hover:bg-slate-950">Avbryt test</Button><Button variant="outline" onClick={()=>setConfirmExit(false)} className="min-h-12 rounded-xl">Fortsätt testet</Button></DialogContent></Dialog>
 <Dialog open={registeredShot!==null} onOpenChange={()=>{}}><DialogContent className="!z-[145] w-[calc(100%-32px)] max-w-sm rounded-3xl bg-white p-6 text-center [&>button]:hidden"><DialogTitle className="text-2xl font-black">Slag {registeredShot?.index} registrerat</DialogTitle><DialogDescription className="sr-only">Bekräftelse på registrerat slag.</DialogDescription>{registeredShot&&<div className="mt-2 grid grid-cols-2 gap-3"><div className="rounded-2xl bg-slate-50 p-4"><p className="text-xs font-bold uppercase tracking-wide text-slate-500">Total längd</p><p className="mt-1 text-2xl font-black text-slate-800">{Math.round(registeredShot.shot.distance)} m</p></div>{!long&&<div className="rounded-2xl bg-slate-50 p-4"><p className="text-xs font-bold uppercase tracking-wide text-slate-500">Sidled</p><p className="mt-1 text-2xl font-black text-slate-800">{Math.round(registeredShot.shot.lateral)} m{registeredShot.shot.lateral>0?<> – {registeredShot.shot.side==="left"?"Vänster":"Höger"}</>:null}</p></div>}</div>}<Button onClick={continueAfterRegistration} className="mt-2 min-h-14 w-full rounded-2xl bg-blue-600 text-base font-black text-white hover:bg-blue-600">{shots.length===3?"Visa resultat":"Fortsätt till slag "+(shots.length+1)}</Button></DialogContent></Dialog>
 {view==="intro"?<div className="space-y-4"><section className="text-center"><p className="text-xs font-black uppercase text-blue-600">{title} Challenge</p><h1 className="mt-1 text-4xl font-black">{long?"Hur långt slår du?":"Hur bra är dina utslag?"}</h1><p className="mx-auto mt-2 max-w-sm text-sm text-slate-600">{long?"Tre drives. Längsta totallängd räknas.":"Tre drives. Mät längd och precision."}</p></section>
 <section className="rounded-3xl border border-blue-100 bg-white px-3 pb-5 pt-4 shadow-sm"><img src="/Off_the_tee.png" alt="" className="mb-4 h-52 w-full rounded-2xl object-cover object-[center_55%]"/><div className="grid grid-cols-3 divide-x divide-slate-100 rounded-2xl bg-slate-50 py-3 text-center">{[[long?"Längsta":"Längd","3 slag"],["HCP","Analys"],[long?"Snitt":"Precision",long?"Ditt test":"Sidled"]].map(([a,b])=><div key={a}><Check className="mx-auto mb-1 h-4 w-4 text-blue-600"/><p className="text-xs font-black">{a}</p><p className="text-[10px] text-slate-500">{b}</p></div>)}</div><Button onClick={start} className="mt-4 min-h-14 w-full rounded-2xl bg-blue-600 text-base font-black text-white hover:bg-blue-600">Starta {title}-Test</Button><p className="mt-3 text-center text-xs font-semibold text-slate-500">3 slag · Driver · {long?"Total längd":"Längd + precision"}</p></section>
 {pb>0&&<div className="mt-4 flex items-center justify-between px-2 py-2 text-slate-900"><span className="flex items-center gap-2 text-sm font-semibold"><Trophy className="h-4 w-4"/>Ditt personbästa</span><strong>{fmt(pb)} m</strong></div>}{long&&<LongDriveLeaderboard sessions={longSessions}/>}</div>
 :view==="countdown"?<div className="fixed inset-0 z-[90] flex flex-col items-center justify-center bg-blue-600 px-6 text-center text-white"><p className="text-xs font-black uppercase tracking-[.18em] text-blue-100">{title} Challenge · 3 slag</p><h1 className="mt-3 text-3xl font-black">Gör dig redo</h1><p className="mt-2 text-sm text-blue-100">Startar om {Math.max(1,Math.ceil(countdown))}</p><div className="relative mt-8 h-40 w-40"><svg className="-rotate-90 h-full w-full" viewBox="0 0 100 100"><circle cx="50" cy="50" r="40" fill="none" stroke="currentColor" strokeWidth="5" className="text-white/20"/><circle cx="50" cy="50" r="40" fill="none" stroke="currentColor" strokeWidth="5" strokeLinecap="round" strokeDasharray="251.2" strokeDashoffset={251.2*(1-Math.max(0,countdown)/3)} className="text-white"/></svg><span className="absolute inset-0 flex items-center justify-center text-6xl font-black">{Math.max(1,Math.ceil(countdown))}</span></div></div>
 :view==="test"?<div className="space-y-3"><section><p className="text-center text-xs font-semibold text-slate-500">{title} Challenge · 3 slag</p><h1 className="mt-2 text-center text-4xl font-black">Slag {shotNo}</h1></section>{shotNo===3&&<p className="rounded-2xl border border-violet-200 bg-violet-50 px-4 py-3 text-center font-bold text-violet-900">Sista slaget – en chans till att slå ditt rekord!</p>}
 <section className="rounded-3xl border border-blue-100 bg-white p-4"><label className="block text-center text-lg font-bold text-slate-600">Total längd</label><div className="my-5 flex items-baseline justify-center"><input inputMode="decimal" value={distance} onChange={e=>{setDistance(e.target.value);setDistanceTouched(true)}} className={`w-36 bg-transparent text-center text-6xl font-black outline-none transition-colors ${distanceTouched?"text-slate-700":"text-slate-400"}`}/><span className="text-lg text-slate-400">m</span></div><div className="grid grid-cols-4 gap-2">{[-10,-5,5,10].map(d=><Button key={d} variant="outline" onClick={()=>{setDistance(String(Math.max(1,Math.min(400,(Number(distance)||0)+d))));setDistanceTouched(true)}} className="bg-white">{d>0?"+":""}{d}</Button>)}</div>
 {!long&&<><div className="my-5 border-t"/><label className="block text-center text-lg font-bold text-slate-600">Sidled från mitten</label><div className="my-4 flex items-baseline justify-center"><span className={`text-4xl font-black transition-colors ${lateralTouched?"text-slate-700":"text-slate-400"}`}>{Math.round(Number(lateral)||0)}</span><span className="ml-1 text-sm text-slate-400">m</span>{(Number(lateral)||0)>0&&side&&<span className="ml-2 text-lg font-bold text-slate-600">– {side==="left"?"Vänster":"Höger"}</span>}</div><div className="mb-2 grid grid-cols-4 gap-2">{[-5,-1,1,5].map(d=><Button key={d} variant="outline" onClick={()=>{const signed=(side==="left"?-(Number(lateral)||0):(Number(lateral)||0))+d;const next=Math.max(-80,Math.min(80,signed));setLateral(String(Math.abs(next)));setSide(next<0?"left":next>0?"right":null);setLateralTouched(next!==0)}} className="bg-white">{d>0?"+":""}{d}</Button>)}</div></>}
 <div className="sticky bottom-3 z-20 mt-8 rounded-2xl border border-blue-100 bg-white/95 p-3 shadow-lg backdrop-blur"><p className="mb-2 text-center text-sm text-slate-600">Slaget var <strong>{Math.round(Number(distance)||0)} m</strong> i längd.{!long?<> Sidled <strong>{Math.round(Number(lateral)||0)} m{(Number(lateral)||0)>0&&side?<> – {side==="left"?"Vänster":"Höger"}</>:null}</strong>.</>:null}</p><Button onClick={add} disabled={!long&&(Number(lateral)||0)>0&&!side} className="min-h-14 w-full rounded-2xl bg-blue-600 text-base font-black text-white hover:bg-blue-600 disabled:bg-slate-300">Registrera slag {shotNo}</Button></div>{shots.length>0&&<Button variant="ghost" onClick={()=>setShots(s=>s.slice(0,-1))} className="mt-1 w-full text-slate-500"><Undo2/>Ändra förra slaget</Button>}</section></div>
 :view==="compiling"?createPortal(<div className="fixed inset-0 z-[100] flex flex-col items-center justify-center bg-gradient-to-b from-blue-600 to-blue-700 p-6 text-center text-white"><span className="mb-7 flex h-16 w-16 items-center justify-center rounded-full bg-white text-blue-600">{compile>=3?<Check className="h-9 w-9"/>:<LoaderCircle className="h-9 w-9 motion-safe:animate-spin"/>}</span><h1 className="text-3xl font-black">{compile>=3?"Resultatet klart":"Sammanställer testet…"}</h1><div className="mt-6 w-full max-w-xs space-y-4 text-left text-blue-100">{["Sammanställer dina tre slag",long?"Beräknar längdresultat":"Beräknar längd och precision","Förbereder din HCP-analys"].map((x,i)=><p key={x} className={`flex items-center gap-3 ${i<=compile?"opacity-100":"opacity-0"}`}>{i<compile||compile>=3?<Check className="h-5 w-5"/>:<LoaderCircle className="h-5 w-5 motion-safe:animate-spin"/>}{x}</p>)}</div></div>,document.body)
 :result?<div className="space-y-4"><section className="relative overflow-hidden rounded-3xl border border-blue-100 bg-white p-5 text-center shadow-sm"><span className="d-sheen pointer-events-none absolute inset-y-0 w-20 -skew-x-12 bg-gradient-to-r from-transparent via-blue-100/80 to-transparent"/><p className="text-xs font-black uppercase text-blue-600">Ditt resultat</p><h1 className="mt-1 text-2xl font-black">{title} klar</h1><p className="mt-4 text-5xl font-black text-blue-700">{fmt(best)} m</p><p className="text-sm text-slate-500">Längsta totallängd</p><div className="mt-5 rounded-2xl bg-slate-50 p-5"><p className="text-sm font-semibold text-slate-500">{long?"Snitt i testet":"Snittlängd"}</p><p className="mt-2 text-3xl font-bold text-slate-600">{fmt(avg)} m</p>{!long&&<p className="mt-1 text-sm text-slate-500">Snitt sidled {fmt(result.avgSidled)} m</p>}</div></section><Button onClick={()=>setAnalysis(true)} className="min-h-14 w-full rounded-2xl bg-blue-600 text-base font-black text-white hover:bg-blue-600">Visa min HCP-analys</Button><Button onClick={start} className="min-h-14 w-full rounded-2xl bg-slate-950 text-white hover:bg-slate-950"><RotateCcw/>Testa igen · 3 slag</Button></div>:null}
 <Dialog open={analysis} onOpenChange={setAnalysis}><DialogContent className="!fixed !inset-0 !h-[100dvh] !max-h-none !w-full !max-w-none !translate-x-0 !translate-y-0 !rounded-none !border-0 !bg-blue-600 !p-0 text-white [&>button]:text-white"><DialogTitle className="sr-only">{title} HCP-analys</DialogTitle><DialogDescription className="sr-only">Ditt estimerade handicap från tre slag.</DialogDescription><div className="relative mx-auto flex h-full w-full max-w-md flex-col justify-center px-6 text-center">{analysisPage===0&&<>{hcpReady&&<ChipCelebration confettiOnly/>}<p className="text-sm font-bold uppercase tracking-widest text-blue-100">{title} HCP-analys</p><h2 className="mt-5 text-3xl font-black">Ditt estimerade HCP</h2><div className="my-8 text-[clamp(88px,27vw,132px)] font-black tabular-nums">{handicapLabel(Math.round(rollingHcp*10)/10)}</div>{hcpReady&&<Button onClick={()=>setAnalysisPage(1)} className="mx-auto min-h-14 w-full max-w-xs rounded-full bg-white font-black text-blue-700 hover:bg-white">Nästa <ArrowRight/></Button>}</>}{analysisPage>0&&<div className="absolute left-6 right-6 top-6 flex justify-center gap-1.5">{Array.from({length:long?6:7},(_,i)=><span key={i} className={`h-1.5 rounded-full ${i===analysisPage-1?"w-6 bg-white":"w-1.5 bg-white/35"}`}/>)}</div>}{analysisPage===1&&result&&!long&&<><ShotAnalysisList title="Dina tre utslag" rows={result.shots.map((shot,i)=>{const shotHcp=offTeeResult(tee([shots[i]])).handicap;return {label:`Slag ${i+1}`,value:`${fmt(shot.total)} m · ${fmt(Math.abs(shots[i].lateral))} m sidled`,grade:shotHcp<=0?"exceptionell":shotHcp<=5?"briljant":shotHcp<=12?"bra":shotHcp<=22?"förväntat":shotHcp<=32?"svag":"stort tapp"}})}/><Button onClick={()=>setAnalysisPage(2)} className="mt-6 min-h-14 w-full rounded-full bg-white font-black text-blue-700 hover:bg-white">Nästa <ArrowRight/></Button></>}{((analysisPage===1&&long)||(analysisPage===2&&!long))&&result&&<><p className="text-sm font-bold uppercase tracking-widest text-blue-100">Jämförelse</p><h2 className="mt-4 text-3xl font-black">{long?"Din längdnivå":"Din drivernivå"}</h2><div className="mt-6 w-full rounded-3xl bg-white p-1 text-slate-950"><DrivingHcpBellCurve hcp={hcp??0}/></div><div className="mt-4 rounded-3xl bg-white/10 p-5 text-left"><p className="flex justify-between"><span>Snittlängd</span><strong>{fmt(result.avgTotal)} m</strong></p>{!long&&<><p className="mt-3 flex justify-between"><span>Snitt sidled</span><strong>{fmt(result.avgSidled)} m</strong></p><p className="mt-3 flex justify-between"><span>Fairway</span><strong>{Math.round(result.fairwayHitPct)} %</strong></p></>}</div><Button onClick={()=>setAnalysisPage(p=>p+1)} className="mt-6 min-h-14 w-full rounded-full bg-white font-black text-blue-700 hover:bg-white">Nästa <ArrowRight/></Button></>}
 {analysisPage===(long?2:3)&&result&&<><p className="text-sm font-bold uppercase tracking-widest text-blue-100">Topprestation</p><h2 className="mt-4 text-3xl font-black">{long?"Din längsta drive":"Ditt bästa kompletta utslag"}</h2><div className="my-7 text-6xl font-black">{fmt(long?best:Math.max(...shots.map(x=>x.distance-Math.abs(x.lateral))))} {long?"m":"poäng"}</div><Button onClick={()=>setAnalysisPage(p=>p+1)} className="min-h-14 w-full rounded-full bg-white font-black text-blue-700 hover:bg-white">Nästa <ArrowRight/></Button></>}
 {analysisPage===(long?3:4)&&<><p className="text-sm font-bold uppercase tracking-widest text-blue-100">Jämförelse</p><h2 className="mt-4 text-3xl font-black">Din åldersgrupp & alla golfare</h2><div className="mt-6 rounded-3xl bg-white p-1 text-slate-950"><HcpComparisonBellCurve hcp={hcp??0} allGolfers={{label:"Alla golfare",mean:17,sd:8}} ageGroup={age?{label:`${age} år`,mean:age<30?12:age<50?15:19,sd:8}:undefined}/></div><Button onClick={()=>setAnalysisPage(p=>p+1)} className="mt-5 min-h-14 w-full rounded-full bg-white font-black text-blue-700 hover:bg-white">Nästa <ArrowRight/></Button></>}
 {analysisPage===(long?4:5)&&<><p className="text-sm font-bold uppercase tracking-widest text-blue-100">Tour / nivå</p><h2 className="mt-4 text-3xl font-black">Mot PGA Tour</h2><div className="mt-7 grid grid-cols-2 gap-3"><div className="rounded-3xl bg-white p-5 text-blue-700"><p>Du</p><strong className="mt-2 block text-4xl">{fmt(best)} m</strong></div><div className="rounded-3xl bg-white/10 p-5"><p>PGA Tour-snitt</p><strong className="mt-2 block text-4xl">≈ {TOUR.carryM} m</strong></div></div><p className="mt-4 text-xs text-blue-100">{long?"Din totaldistans jämförs här orienterande mot Tourens carryreferens.":"Längdreferensen kompletteras av din precision i HCP-resultatet."}</p><Button onClick={()=>setAnalysisPage(p=>p+1)} className="mt-5 min-h-14 w-full rounded-full bg-white font-black text-blue-700 hover:bg-white">Nästa <ArrowRight/></Button></>}
 {analysisPage===(long?5:6)&&<><p className="text-sm font-bold uppercase tracking-widest text-blue-100">Din potential</p><h2 className="mt-4 text-3xl font-black">Det här tar du med dig</h2><div className="mt-6 rounded-3xl bg-white/10 p-5"><p className="text-5xl font-black">{fmt(best)} m</p><p className="mt-2 text-blue-100">{long?"Din bästa totallängd idag":"Din bästa kombination av längd och precision visar nivån du kan nå."}</p></div><Button onClick={()=>setAnalysis(false)} className="mt-6 min-h-14 w-full rounded-full bg-white font-black text-blue-700 hover:bg-white">Till resultatet</Button></>}</div></DialogContent></Dialog>
 </main>
}
