import { createPortal } from "react-dom";
import { useEffect, useMemo, useRef, useState } from "react";
import { ArrowLeft, Check, LoaderCircle, RotateCcw, Trophy, Undo2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogTitle } from "@/components/ui/dialog";
import { offTeeResult, handicapLabel, type TeeShot } from "@/lib/offtee";
import { loadLongDriveSessions, saveLongDriveSession, sessionBest, todayISO } from "@/lib/longdrive";
import { useChipScreenColor } from "@/lib/use-chip-screen-color";
type Mode="longdrive"|"offtee"; type Shot={distance:number;lateral:number;side:"left"|"right"|"center"}; type Saved={id:string;at:number;shots:Shot[]};
const KEY="sg4-offtee-three-shot-v1",fmt=(n:number)=>n.toFixed(1).replace(".",",");
const tee=(a:Shot[]):TeeShot[]=>a.map((s,i)=>({index:i+1,filled:true,total:s.distance,sidled:s.lateral,direction:s.side==="left"?"left":"right"}));
function loadOfftee():Saved[]{try{const v=JSON.parse(localStorage.getItem(KEY)??"[]");return Array.isArray(v)?v:[]}catch{return[]}}
function saveOfftee(x:Saved){localStorage.setItem(KEY,JSON.stringify([...loadOfftee(),x].slice(-30)))}
export function ThreeShotDriverTest({mode,onExit}:{mode:Mode;onExit:()=>void}){
 const long=mode==="longdrive",title=long?"Long Drive":"Utslag";
 const [view,setView]=useState<"intro"|"countdown"|"test"|"compiling"|"result">("intro"),[countdown,setCountdown]=useState(3),[shots,setShots]=useState<Shot[]>([]);
 const [distance,setDistance]=useState(long?"250":"220"),[lateral,setLateral]=useState("0"),[side,setSide]=useState<"left"|"right">("right"),[compile,setCompile]=useState(0);
 const [confirmExit,setConfirmExit]=useState(false),[analysis,setAnalysis]=useState(false),[hcpReady,setHcpReady]=useState(false); const timers=useRef<number[]>([]);
 useChipScreenColor(view==="countdown"||view==="compiling"||analysis);
 const result=useMemo(()=>shots.length===3?offTeeResult(tee(shots)):null,[shots]),best=Math.max(0,...shots.map(s=>s.distance)),avg=shots.length?shots.reduce((a,s)=>a+s.distance,0)/shots.length:0;
 const pb=typeof window==="undefined"?0:long?Math.max(0,...loadLongDriveSessions().map(sessionBest)):Math.max(0,...loadOfftee().flatMap(t=>t.shots.map(s=>s.distance)));
 const clear=()=>{timers.current.forEach(window.clearTimeout);timers.current=[]}; useEffect(()=>clear,[]);
 useEffect(()=>{if(view!=="countdown")return;setCountdown(3);const start=performance.now(),duration=2400,id=window.setInterval(()=>{const left=Math.max(0,duration-(performance.now()-start));setCountdown(left/800);if(left<=0){window.clearInterval(id);setView("test")}},40);return()=>window.clearInterval(id)},[view]);
 useEffect(()=>{if(view!=="compiling")return;setCompile(0);clear();timers.current=[window.setTimeout(()=>setCompile(1),850),window.setTimeout(()=>setCompile(2),1750),window.setTimeout(()=>setCompile(3),2650),window.setTimeout(()=>setView("result"),3400)];return clear},[view]);
 useEffect(()=>{if(!analysis)return;setHcpReady(false);const r=window.matchMedia("(prefers-reduced-motion: reduce)").matches,id=window.setTimeout(()=>setHcpReady(true),r?0:1500);return()=>window.clearTimeout(id)},[analysis]);
 function start(){setShots([]);setDistance(long?"250":"220");setLateral("0");setSide("right");setView("countdown")}
 function add(){const d=Number(distance.replace(",",".")),l=long?0:Number(lateral.replace(",","."));if(!Number.isFinite(d)||d<=0||d>400||!Number.isFinite(l)||l<0||l>200)return;const next=[...shots,{distance:d,lateral:l,side:l===0?"center":side} as Shot];setShots(next);if(next.length===3){if(long)saveLongDriveSession({date:todayISO(),carries:next.map(s=>s.distance),unit:"m"});else saveOfftee({id:crypto.randomUUID(),at:Date.now(),shots:next});setView("compiling")}}
 function abort(){clear();setConfirmExit(false);setShots([]);onExit()} const shotNo=Math.min(3,shots.length+1),hcp=result?.handicap??null;
 return <main className="mx-auto min-h-[calc(100dvh-58px)] max-w-md bg-slate-50 px-4 pb-[max(24px,env(safe-area-inset-bottom))] pt-4 text-slate-950">
 <style>{`@keyframes dSheen{0%{transform:translateX(-140%);opacity:0}12%{opacity:1}88%{opacity:1}100%{transform:translateX(260%);opacity:0}}.d-sheen{opacity:0;animation:dSheen 1.15s ease .2s 1}@media(prefers-reduced-motion:reduce){.d-sheen{animation:none!important}}`}</style>
 {view!=="intro"&&<Button variant="ghost" aria-label="Avbryt test" onClick={()=>setConfirmExit(true)} className={`fixed left-3 top-[max(10px,env(safe-area-inset-top))] z-[130] h-11 w-11 rounded-full p-0 ${view==="countdown"||view==="compiling"?"text-white":"text-slate-700"}`}><ArrowLeft/></Button>}
 <Dialog open={confirmExit} onOpenChange={setConfirmExit}><DialogContent className="!z-[140] w-[calc(100%-32px)] max-w-sm rounded-3xl bg-white p-6"><DialogTitle className="text-2xl font-black">Avbryta testet?</DialogTitle><DialogDescription>Dina slag i det här testet sparas inte.</DialogDescription><Button onClick={abort} className="min-h-12 rounded-xl bg-slate-950 text-white">Avbryt test</Button><Button variant="outline" onClick={()=>setConfirmExit(false)} className="min-h-12 rounded-xl">Fortsätt testet</Button></DialogContent></Dialog>
 {view==="intro"?<div className="space-y-4"><section className="text-center"><p className="text-xs font-black uppercase text-blue-600">{title} Challenge</p><h1 className="mt-1 text-4xl font-black">{long?"Hur långt slår du?":"Hur bra är dina utslag?"}</h1><p className="mx-auto mt-2 max-w-sm text-sm text-slate-600">{long?"Tre drives. Längsta carry räknas.":"Tre drives. Mät längd och precision."}</p></section>
 <section className="rounded-3xl border border-blue-100 bg-white px-3 pb-5 pt-4 shadow-sm"><img src="/Off_the_tee.png" alt="" className="mb-4 h-52 w-full rounded-2xl object-cover object-[center_55%]"/><div className="grid grid-cols-3 divide-x divide-slate-100 rounded-2xl bg-slate-50 py-3 text-center">{[[long?"Längsta":"Längd","3 slag"],["HCP","Analys"],[long?"Snitt":"Precision",long?"Ditt test":"Sidled"]].map(([a,b])=><div key={a}><Check className="mx-auto mb-1 h-4 w-4 text-blue-600"/><p className="text-xs font-black">{a}</p><p className="text-[10px] text-slate-500">{b}</p></div>)}</div><Button onClick={start} className="mt-4 min-h-14 w-full rounded-2xl bg-blue-600 text-base font-black text-white">Starta {title}-Test</Button><p className="mt-3 text-center text-xs font-semibold text-slate-500">3 slag · Driver · {long?"Carry":"Längd + precision"}</p></section>
 {pb>0&&<div className="flex items-center justify-between px-2 py-2"><span className="flex items-center gap-2 text-sm font-semibold"><Trophy className="h-4 w-4"/>Ditt personbästa</span><strong>{fmt(pb)} m</strong></div>}</div>
 :view==="countdown"?<div className="fixed inset-0 z-[90] flex flex-col items-center justify-center bg-blue-600 px-6 text-center text-white"><p className="text-xs font-black uppercase tracking-[.18em] text-blue-100">{title} Challenge · 3 slag</p><h1 className="mt-3 text-3xl font-black">Gör dig redo</h1><p className="mt-2 text-sm text-blue-100">Startar om {Math.max(1,Math.ceil(countdown))}</p><div className="relative mt-8 h-40 w-40"><svg className="-rotate-90 h-full w-full" viewBox="0 0 100 100"><circle cx="50" cy="50" r="40" fill="none" stroke="currentColor" strokeWidth="5" className="text-white/20"/><circle cx="50" cy="50" r="40" fill="none" stroke="currentColor" strokeWidth="5" strokeLinecap="round" strokeDasharray="251.2" strokeDashoffset={251.2*(1-Math.max(0,countdown)/3)} className="text-white"/></svg><span className="absolute inset-0 flex items-center justify-center text-6xl font-black">{Math.max(1,Math.ceil(countdown))}</span></div></div>
 :view==="test"?<div className="space-y-3"><section><p className="text-center text-xs font-semibold text-slate-500">{title} Challenge · 3 slag</p><h1 className="mt-2 text-center text-4xl font-black">Slag {shotNo}</h1></section>{shotNo===3&&<p className="rounded-2xl border border-violet-200 bg-violet-50 px-4 py-3 text-center font-bold text-violet-900">Sista slaget – en chans till att slå ditt rekord!</p>}
 <section className="rounded-3xl border border-blue-100 bg-white p-4"><label className="block text-center text-sm font-semibold text-slate-500">{long?"Carry":"Total längd"}</label><div className="my-5 flex items-baseline justify-center"><input inputMode="decimal" value={distance} onChange={e=>setDistance(e.target.value)} className="w-36 bg-transparent text-center text-6xl font-black text-blue-700 outline-none"/><span className="text-lg text-slate-400">m</span></div><div className="grid grid-cols-4 gap-2">{[-10,-5,5,10].map(d=><Button key={d} variant="outline" onClick={()=>setDistance(String(Math.max(1,Math.min(400,(Number(distance)||0)+d))))}>{d>0?"+":""}{d}</Button>)}</div>
 {!long&&<><div className="my-4 border-t"/><label className="block text-center text-sm font-semibold text-slate-500">Sidled från mitten</label><div className="my-3 flex items-baseline justify-center"><input inputMode="decimal" value={lateral} onChange={e=>setLateral(e.target.value)} className="w-24 bg-transparent text-center text-4xl font-black outline-none"/><span className="text-sm text-slate-400">m</span></div><div className="grid grid-cols-2 gap-2">{(["left","right"] as const).map(v=><Button key={v} variant={side===v?"default":"outline"} onClick={()=>setSide(v)} className={side===v?"bg-slate-600":""}>{v==="left"?"Vänster":"Höger"}</Button>)}</div></>}
 <Button onClick={add} className="mt-4 min-h-14 w-full rounded-2xl bg-blue-600 text-base font-black text-white">Registrera slag</Button>{shots.length>0&&<Button variant="ghost" onClick={()=>setShots(s=>s.slice(0,-1))} className="mt-1 w-full text-slate-500"><Undo2/>Ändra förra slaget</Button>}</section></div>
 :view==="compiling"?createPortal(<div className="fixed inset-0 z-[100] flex flex-col items-center justify-center bg-gradient-to-b from-blue-600 to-blue-700 p-6 text-center text-white"><span className="mb-7 flex h-16 w-16 items-center justify-center rounded-full bg-white text-blue-600">{compile>=3?<Check className="h-9 w-9"/>:<LoaderCircle className="h-9 w-9 motion-safe:animate-spin"/>}</span><h1 className="text-3xl font-black">{compile>=3?"Resultatet klart":"Sammanställer testet…"}</h1><div className="mt-6 w-full max-w-xs space-y-4 text-left text-blue-100">{["Sammanställer dina tre slag",long?"Beräknar längdresultat":"Beräknar längd och precision","Förbereder din HCP-analys"].map((x,i)=><p key={x} className={`flex items-center gap-3 ${i<=compile?"opacity-100":"opacity-0"}`}>{i<compile||compile>=3?<Check className="h-5 w-5"/>:<LoaderCircle className="h-5 w-5 motion-safe:animate-spin"/>}{x}</p>)}</div></div>,document.body)
 :result?<div className="space-y-4"><section className="relative overflow-hidden rounded-3xl border border-blue-100 bg-white p-5 text-center shadow-sm"><span className="d-sheen pointer-events-none absolute inset-y-0 w-20 -skew-x-12 bg-gradient-to-r from-transparent via-blue-100/80 to-transparent"/><p className="text-xs font-black uppercase text-blue-600">Ditt resultat</p><h1 className="mt-1 text-2xl font-black">{title} klar</h1><p className="mt-4 text-5xl font-black text-blue-700">{fmt(best)} m</p><p className="text-sm text-slate-500">{long?"Längsta carry":"Längsta drive"}</p><div className="mt-5 rounded-2xl bg-slate-50 p-5"><p className="text-sm font-semibold text-slate-500">{long?"Snitt i testet":"Snittlängd"}</p><p className="mt-2 text-3xl font-bold text-slate-600">{fmt(avg)} m</p>{!long&&<p className="mt-1 text-sm text-slate-500">Snitt sidled {fmt(result.avgSidled)} m</p>}</div></section><Button onClick={()=>setAnalysis(true)} className="min-h-14 w-full rounded-2xl bg-blue-600 text-base font-black text-white">Visa min HCP-analys</Button><Button onClick={start} className="min-h-14 w-full rounded-2xl bg-slate-950 text-white"><RotateCcw/>Testa igen · 3 slag</Button></div>:null}
 <Dialog open={analysis} onOpenChange={setAnalysis}><DialogContent className="!fixed !inset-0 !h-[100dvh] !max-h-none !w-full !max-w-none !translate-x-0 !translate-y-0 !rounded-none !border-0 !bg-blue-600 !p-0 text-white [&>button]:text-white"><DialogTitle className="sr-only">{title} HCP-analys</DialogTitle><DialogDescription className="sr-only">Ditt estimerade handicap från tre slag.</DialogDescription><div className="flex h-full flex-col items-center justify-center px-6 text-center"><p className="text-sm font-bold uppercase tracking-widest text-blue-100">{title} HCP-analys</p><h2 className="mt-5 text-3xl font-black">{hcpReady?"Ditt estimerade HCP":"Analyserar dina tre slag…"}</h2><div className="my-8 text-[clamp(88px,27vw,132px)] font-black">{hcpReady&&hcp!==null?handicapLabel(hcp):<LoaderCircle className="mx-auto h-16 w-16 motion-safe:animate-spin"/>}</div>{hcpReady&&result&&<div className="w-full max-w-xs rounded-3xl bg-white/10 p-5 text-left"><p className="flex justify-between"><span>{long?"Snittlängd":"Snittlängd"}</span><strong>{fmt(result.avgTotal)} m</strong></p>{!long&&<><p className="mt-3 flex justify-between"><span>Snitt sidled</span><strong>{fmt(result.avgSidled)} m</strong></p><p className="mt-3 flex justify-between"><span>Fairway</span><strong>{Math.round(result.fairwayHitPct)} %</strong></p></>}</div>}<Button onClick={()=>setAnalysis(false)} className="mt-7 min-h-14 w-full max-w-xs rounded-full bg-white font-black text-blue-700 hover:bg-blue-50">Till resultatet</Button></div></DialogContent></Dialog>
 </main>
}
