/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WedgeRouteImport } from './routes/wedge'
import { Route as TraningRouteImport } from './routes/traning'
import { Route as TornadoRouteImport } from './routes/tornado'
import { Route as TopplistaRouteImport } from './routes/topplista'
import { Route as TeeshotRouteImport } from './routes/teeshot'
import { Route as SpeedRouteImport } from './routes/speed'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ShapingRouteImport } from './routes/shaping'
import { Route as PitchRouteImport } from './routes/pitch'
import { Route as Par3RouteImport } from './routes/par3'
import { Route as LongdriveRouteImport } from './routes/longdrive'
import { Route as LagputtRouteImport } from './routes/lagputt'
import { Route as KortputtRouteImport } from './routes/kortputt'
import { Route as KontoRouteImport } from './routes/konto'
import { Route as FairwayRouteImport } from './routes/fairway'
import { Route as DrillRouteImport } from './routes/drill'
import { Route as CombineRouteImport } from './routes/combine'
import { Route as ChipRouteImport } from './routes/chip'
import { Route as BunkerRouteImport } from './routes/bunker'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FramstegIndexRouteImport } from './routes/framsteg.index'
import { Route as KategoriSlugRouteImport } from './routes/kategori.$slug'
import { Route as FramstegSlugRouteImport } from './routes/framsteg.$slug'
import { Route as FramstegSlugTestRouteImport } from './routes/framsteg.$slug.$test'

const WedgeRoute = WedgeRouteImport.update({
  id: '/wedge',
  path: '/wedge',
  getParentRoute: () => rootRouteImport,
} as any)
const TraningRoute = TraningRouteImport.update({
  id: '/traning',
  path: '/traning',
  getParentRoute: () => rootRouteImport,
} as any)
const TornadoRoute = TornadoRouteImport.update({
  id: '/tornado',
  path: '/tornado',
  getParentRoute: () => rootRouteImport,
} as any)
const TopplistaRoute = TopplistaRouteImport.update({
  id: '/topplista',
  path: '/topplista',
  getParentRoute: () => rootRouteImport,
} as any)
const TeeshotRoute = TeeshotRouteImport.update({
  id: '/teeshot',
  path: '/teeshot',
  getParentRoute: () => rootRouteImport,
} as any)
const SpeedRoute = SpeedRouteImport.update({
  id: '/speed',
  path: '/speed',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ShapingRoute = ShapingRouteImport.update({
  id: '/shaping',
  path: '/shaping',
  getParentRoute: () => rootRouteImport,
} as any)
const PitchRoute = PitchRouteImport.update({
  id: '/pitch',
  path: '/pitch',
  getParentRoute: () => rootRouteImport,
} as any)
const Par3Route = Par3RouteImport.update({
  id: '/par3',
  path: '/par3',
  getParentRoute: () => rootRouteImport,
} as any)
const LongdriveRoute = LongdriveRouteImport.update({
  id: '/longdrive',
  path: '/longdrive',
  getParentRoute: () => rootRouteImport,
} as any)
const LagputtRoute = LagputtRouteImport.update({
  id: '/lagputt',
  path: '/lagputt',
  getParentRoute: () => rootRouteImport,
} as any)
const KortputtRoute = KortputtRouteImport.update({
  id: '/kortputt',
  path: '/kortputt',
  getParentRoute: () => rootRouteImport,
} as any)
const KontoRoute = KontoRouteImport.update({
  id: '/konto',
  path: '/konto',
  getParentRoute: () => rootRouteImport,
} as any)
const FairwayRoute = FairwayRouteImport.update({
  id: '/fairway',
  path: '/fairway',
  getParentRoute: () => rootRouteImport,
} as any)
const DrillRoute = DrillRouteImport.update({
  id: '/drill',
  path: '/drill',
  getParentRoute: () => rootRouteImport,
} as any)
const CombineRoute = CombineRouteImport.update({
  id: '/combine',
  path: '/combine',
  getParentRoute: () => rootRouteImport,
} as any)
const ChipRoute = ChipRouteImport.update({
  id: '/chip',
  path: '/chip',
  getParentRoute: () => rootRouteImport,
} as any)
const BunkerRoute = BunkerRouteImport.update({
  id: '/bunker',
  path: '/bunker',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FramstegIndexRoute = FramstegIndexRouteImport.update({
  id: '/framsteg/',
  path: '/framsteg/',
  getParentRoute: () => rootRouteImport,
} as any)
const KategoriSlugRoute = KategoriSlugRouteImport.update({
  id: '/kategori/$slug',
  path: '/kategori/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const FramstegSlugRoute = FramstegSlugRouteImport.update({
  id: '/framsteg/$slug',
  path: '/framsteg/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const FramstegSlugTestRoute = FramstegSlugTestRouteImport.update({
  id: '/$test',
  path: '/$test',
  getParentRoute: () => FramstegSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bunker': typeof BunkerRoute
  '/chip': typeof ChipRoute
  '/combine': typeof CombineRoute
  '/drill': typeof DrillRoute
  '/fairway': typeof FairwayRoute
  '/konto': typeof KontoRoute
  '/kortputt': typeof KortputtRoute
  '/lagputt': typeof LagputtRoute
  '/longdrive': typeof LongdriveRoute
  '/par3': typeof Par3Route
  '/pitch': typeof PitchRoute
  '/shaping': typeof ShapingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/speed': typeof SpeedRoute
  '/teeshot': typeof TeeshotRoute
  '/topplista': typeof TopplistaRoute
  '/tornado': typeof TornadoRoute
  '/traning': typeof TraningRoute
  '/wedge': typeof WedgeRoute
  '/framsteg/$slug': typeof FramstegSlugRouteWithChildren
  '/kategori/$slug': typeof KategoriSlugRoute
  '/framsteg/': typeof FramstegIndexRoute
  '/framsteg/$slug/$test': typeof FramstegSlugTestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bunker': typeof BunkerRoute
  '/chip': typeof ChipRoute
  '/combine': typeof CombineRoute
  '/drill': typeof DrillRoute
  '/fairway': typeof FairwayRoute
  '/konto': typeof KontoRoute
  '/kortputt': typeof KortputtRoute
  '/lagputt': typeof LagputtRoute
  '/longdrive': typeof LongdriveRoute
  '/par3': typeof Par3Route
  '/pitch': typeof PitchRoute
  '/shaping': typeof ShapingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/speed': typeof SpeedRoute
  '/teeshot': typeof TeeshotRoute
  '/topplista': typeof TopplistaRoute
  '/tornado': typeof TornadoRoute
  '/traning': typeof TraningRoute
  '/wedge': typeof WedgeRoute
  '/framsteg/$slug': typeof FramstegSlugRouteWithChildren
  '/kategori/$slug': typeof KategoriSlugRoute
  '/framsteg': typeof FramstegIndexRoute
  '/framsteg/$slug/$test': typeof FramstegSlugTestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bunker': typeof BunkerRoute
  '/chip': typeof ChipRoute
  '/combine': typeof CombineRoute
  '/drill': typeof DrillRoute
  '/fairway': typeof FairwayRoute
  '/konto': typeof KontoRoute
  '/kortputt': typeof KortputtRoute
  '/lagputt': typeof LagputtRoute
  '/longdrive': typeof LongdriveRoute
  '/par3': typeof Par3Route
  '/pitch': typeof PitchRoute
  '/shaping': typeof ShapingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/speed': typeof SpeedRoute
  '/teeshot': typeof TeeshotRoute
  '/topplista': typeof TopplistaRoute
  '/tornado': typeof TornadoRoute
  '/traning': typeof TraningRoute
  '/wedge': typeof WedgeRoute
  '/framsteg/$slug': typeof FramstegSlugRouteWithChildren
  '/kategori/$slug': typeof KategoriSlugRoute
  '/framsteg/': typeof FramstegIndexRoute
  '/framsteg/$slug/$test': typeof FramstegSlugTestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bunker'
    | '/chip'
    | '/combine'
    | '/drill'
    | '/fairway'
    | '/konto'
    | '/kortputt'
    | '/lagputt'
    | '/longdrive'
    | '/par3'
    | '/pitch'
    | '/shaping'
    | '/sitemap.xml'
    | '/speed'
    | '/teeshot'
    | '/topplista'
    | '/tornado'
    | '/traning'
    | '/wedge'
    | '/framsteg/$slug'
    | '/kategori/$slug'
    | '/framsteg/'
    | '/framsteg/$slug/$test'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bunker'
    | '/chip'
    | '/combine'
    | '/drill'
    | '/fairway'
    | '/konto'
    | '/kortputt'
    | '/lagputt'
    | '/longdrive'
    | '/par3'
    | '/pitch'
    | '/shaping'
    | '/sitemap.xml'
    | '/speed'
    | '/teeshot'
    | '/topplista'
    | '/tornado'
    | '/traning'
    | '/wedge'
    | '/framsteg/$slug'
    | '/kategori/$slug'
    | '/framsteg'
    | '/framsteg/$slug/$test'
  id:
    | '__root__'
    | '/'
    | '/bunker'
    | '/chip'
    | '/combine'
    | '/drill'
    | '/fairway'
    | '/konto'
    | '/kortputt'
    | '/lagputt'
    | '/longdrive'
    | '/par3'
    | '/pitch'
    | '/shaping'
    | '/sitemap.xml'
    | '/speed'
    | '/teeshot'
    | '/topplista'
    | '/tornado'
    | '/traning'
    | '/wedge'
    | '/framsteg/$slug'
    | '/kategori/$slug'
    | '/framsteg/'
    | '/framsteg/$slug/$test'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BunkerRoute: typeof BunkerRoute
  ChipRoute: typeof ChipRoute
  CombineRoute: typeof CombineRoute
  DrillRoute: typeof DrillRoute
  FairwayRoute: typeof FairwayRoute
  KontoRoute: typeof KontoRoute
  KortputtRoute: typeof KortputtRoute
  LagputtRoute: typeof LagputtRoute
  LongdriveRoute: typeof LongdriveRoute
  Par3Route: typeof Par3Route
  PitchRoute: typeof PitchRoute
  ShapingRoute: typeof ShapingRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SpeedRoute: typeof SpeedRoute
  TeeshotRoute: typeof TeeshotRoute
  TopplistaRoute: typeof TopplistaRoute
  TornadoRoute: typeof TornadoRoute
  TraningRoute: typeof TraningRoute
  WedgeRoute: typeof WedgeRoute
  FramstegSlugRoute: typeof FramstegSlugRouteWithChildren
  KategoriSlugRoute: typeof KategoriSlugRoute
  FramstegIndexRoute: typeof FramstegIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wedge': {
      id: '/wedge'
      path: '/wedge'
      fullPath: '/wedge'
      preLoaderRoute: typeof WedgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/traning': {
      id: '/traning'
      path: '/traning'
      fullPath: '/traning'
      preLoaderRoute: typeof TraningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tornado': {
      id: '/tornado'
      path: '/tornado'
      fullPath: '/tornado'
      preLoaderRoute: typeof TornadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topplista': {
      id: '/topplista'
      path: '/topplista'
      fullPath: '/topplista'
      preLoaderRoute: typeof TopplistaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teeshot': {
      id: '/teeshot'
      path: '/teeshot'
      fullPath: '/teeshot'
      preLoaderRoute: typeof TeeshotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/speed': {
      id: '/speed'
      path: '/speed'
      fullPath: '/speed'
      preLoaderRoute: typeof SpeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shaping': {
      id: '/shaping'
      path: '/shaping'
      fullPath: '/shaping'
      preLoaderRoute: typeof ShapingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pitch': {
      id: '/pitch'
      path: '/pitch'
      fullPath: '/pitch'
      preLoaderRoute: typeof PitchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/par3': {
      id: '/par3'
      path: '/par3'
      fullPath: '/par3'
      preLoaderRoute: typeof Par3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/longdrive': {
      id: '/longdrive'
      path: '/longdrive'
      fullPath: '/longdrive'
      preLoaderRoute: typeof LongdriveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lagputt': {
      id: '/lagputt'
      path: '/lagputt'
      fullPath: '/lagputt'
      preLoaderRoute: typeof LagputtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kortputt': {
      id: '/kortputt'
      path: '/kortputt'
      fullPath: '/kortputt'
      preLoaderRoute: typeof KortputtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/konto': {
      id: '/konto'
      path: '/konto'
      fullPath: '/konto'
      preLoaderRoute: typeof KontoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fairway': {
      id: '/fairway'
      path: '/fairway'
      fullPath: '/fairway'
      preLoaderRoute: typeof FairwayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drill': {
      id: '/drill'
      path: '/drill'
      fullPath: '/drill'
      preLoaderRoute: typeof DrillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/combine': {
      id: '/combine'
      path: '/combine'
      fullPath: '/combine'
      preLoaderRoute: typeof CombineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chip': {
      id: '/chip'
      path: '/chip'
      fullPath: '/chip'
      preLoaderRoute: typeof ChipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bunker': {
      id: '/bunker'
      path: '/bunker'
      fullPath: '/bunker'
      preLoaderRoute: typeof BunkerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/framsteg/': {
      id: '/framsteg/'
      path: '/framsteg'
      fullPath: '/framsteg/'
      preLoaderRoute: typeof FramstegIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kategori/$slug': {
      id: '/kategori/$slug'
      path: '/kategori/$slug'
      fullPath: '/kategori/$slug'
      preLoaderRoute: typeof KategoriSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/framsteg/$slug': {
      id: '/framsteg/$slug'
      path: '/framsteg/$slug'
      fullPath: '/framsteg/$slug'
      preLoaderRoute: typeof FramstegSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/framsteg/$slug/$test': {
      id: '/framsteg/$slug/$test'
      path: '/$test'
      fullPath: '/framsteg/$slug/$test'
      preLoaderRoute: typeof FramstegSlugTestRouteImport
      parentRoute: typeof FramstegSlugRoute
    }
  }
}

interface FramstegSlugRouteChildren {
  FramstegSlugTestRoute: typeof FramstegSlugTestRoute
}

const FramstegSlugRouteChildren: FramstegSlugRouteChildren = {
  FramstegSlugTestRoute: FramstegSlugTestRoute,
}

const FramstegSlugRouteWithChildren = FramstegSlugRoute._addFileChildren(
  FramstegSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BunkerRoute: BunkerRoute,
  ChipRoute: ChipRoute,
  CombineRoute: CombineRoute,
  DrillRoute: DrillRoute,
  FairwayRoute: FairwayRoute,
  KontoRoute: KontoRoute,
  KortputtRoute: KortputtRoute,
  LagputtRoute: LagputtRoute,
  LongdriveRoute: LongdriveRoute,
  Par3Route: Par3Route,
  PitchRoute: PitchRoute,
  ShapingRoute: ShapingRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SpeedRoute: SpeedRoute,
  TeeshotRoute: TeeshotRoute,
  TopplistaRoute: TopplistaRoute,
  TornadoRoute: TornadoRoute,
  TraningRoute: TraningRoute,
  WedgeRoute: WedgeRoute,
  FramstegSlugRoute: FramstegSlugRouteWithChildren,
  KategoriSlugRoute: KategoriSlugRoute,
  FramstegIndexRoute: FramstegIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
