/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TopplistaRouteImport } from './routes/topplista'
import { Route as SpeedRouteImport } from './routes/speed'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as LongdriveRouteImport } from './routes/longdrive'
import { Route as KontoRouteImport } from './routes/konto'
import { Route as HistorikRouteImport } from './routes/historik'
import { Route as FairwayRouteImport } from './routes/fairway'
import { Route as DrillRouteImport } from './routes/drill'
import { Route as BunkerRouteImport } from './routes/bunker'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KategoriSlugRouteImport } from './routes/kategori.$slug'

const TopplistaRoute = TopplistaRouteImport.update({
  id: '/topplista',
  path: '/topplista',
  getParentRoute: () => rootRouteImport,
} as any)
const SpeedRoute = SpeedRouteImport.update({
  id: '/speed',
  path: '/speed',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LongdriveRoute = LongdriveRouteImport.update({
  id: '/longdrive',
  path: '/longdrive',
  getParentRoute: () => rootRouteImport,
} as any)
const KontoRoute = KontoRouteImport.update({
  id: '/konto',
  path: '/konto',
  getParentRoute: () => rootRouteImport,
} as any)
const HistorikRoute = HistorikRouteImport.update({
  id: '/historik',
  path: '/historik',
  getParentRoute: () => rootRouteImport,
} as any)
const FairwayRoute = FairwayRouteImport.update({
  id: '/fairway',
  path: '/fairway',
  getParentRoute: () => rootRouteImport,
} as any)
const DrillRoute = DrillRouteImport.update({
  id: '/drill',
  path: '/drill',
  getParentRoute: () => rootRouteImport,
} as any)
const BunkerRoute = BunkerRouteImport.update({
  id: '/bunker',
  path: '/bunker',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KategoriSlugRoute = KategoriSlugRouteImport.update({
  id: '/kategori/$slug',
  path: '/kategori/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bunker': typeof BunkerRoute
  '/drill': typeof DrillRoute
  '/fairway': typeof FairwayRoute
  '/historik': typeof HistorikRoute
  '/konto': typeof KontoRoute
  '/longdrive': typeof LongdriveRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/speed': typeof SpeedRoute
  '/topplista': typeof TopplistaRoute
  '/kategori/$slug': typeof KategoriSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bunker': typeof BunkerRoute
  '/drill': typeof DrillRoute
  '/fairway': typeof FairwayRoute
  '/historik': typeof HistorikRoute
  '/konto': typeof KontoRoute
  '/longdrive': typeof LongdriveRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/speed': typeof SpeedRoute
  '/topplista': typeof TopplistaRoute
  '/kategori/$slug': typeof KategoriSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bunker': typeof BunkerRoute
  '/drill': typeof DrillRoute
  '/fairway': typeof FairwayRoute
  '/historik': typeof HistorikRoute
  '/konto': typeof KontoRoute
  '/longdrive': typeof LongdriveRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/speed': typeof SpeedRoute
  '/topplista': typeof TopplistaRoute
  '/kategori/$slug': typeof KategoriSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bunker'
    | '/drill'
    | '/fairway'
    | '/historik'
    | '/konto'
    | '/longdrive'
    | '/sitemap.xml'
    | '/speed'
    | '/topplista'
    | '/kategori/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bunker'
    | '/drill'
    | '/fairway'
    | '/historik'
    | '/konto'
    | '/longdrive'
    | '/sitemap.xml'
    | '/speed'
    | '/topplista'
    | '/kategori/$slug'
  id:
    | '__root__'
    | '/'
    | '/bunker'
    | '/drill'
    | '/fairway'
    | '/historik'
    | '/konto'
    | '/longdrive'
    | '/sitemap.xml'
    | '/speed'
    | '/topplista'
    | '/kategori/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BunkerRoute: typeof BunkerRoute
  DrillRoute: typeof DrillRoute
  FairwayRoute: typeof FairwayRoute
  HistorikRoute: typeof HistorikRoute
  KontoRoute: typeof KontoRoute
  LongdriveRoute: typeof LongdriveRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SpeedRoute: typeof SpeedRoute
  TopplistaRoute: typeof TopplistaRoute
  KategoriSlugRoute: typeof KategoriSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/topplista': {
      id: '/topplista'
      path: '/topplista'
      fullPath: '/topplista'
      preLoaderRoute: typeof TopplistaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/speed': {
      id: '/speed'
      path: '/speed'
      fullPath: '/speed'
      preLoaderRoute: typeof SpeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/longdrive': {
      id: '/longdrive'
      path: '/longdrive'
      fullPath: '/longdrive'
      preLoaderRoute: typeof LongdriveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/konto': {
      id: '/konto'
      path: '/konto'
      fullPath: '/konto'
      preLoaderRoute: typeof KontoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historik': {
      id: '/historik'
      path: '/historik'
      fullPath: '/historik'
      preLoaderRoute: typeof HistorikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fairway': {
      id: '/fairway'
      path: '/fairway'
      fullPath: '/fairway'
      preLoaderRoute: typeof FairwayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drill': {
      id: '/drill'
      path: '/drill'
      fullPath: '/drill'
      preLoaderRoute: typeof DrillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bunker': {
      id: '/bunker'
      path: '/bunker'
      fullPath: '/bunker'
      preLoaderRoute: typeof BunkerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kategori/$slug': {
      id: '/kategori/$slug'
      path: '/kategori/$slug'
      fullPath: '/kategori/$slug'
      preLoaderRoute: typeof KategoriSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BunkerRoute: BunkerRoute,
  DrillRoute: DrillRoute,
  FairwayRoute: FairwayRoute,
  HistorikRoute: HistorikRoute,
  KontoRoute: KontoRoute,
  LongdriveRoute: LongdriveRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SpeedRoute: SpeedRoute,
  TopplistaRoute: TopplistaRoute,
  KategoriSlugRoute: KategoriSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
